"use strict";
/* LENTERA KECIL — Stories v3: 38 cerita, lokal + mancanegara */
const DB = [
  /* ─────────────────────────────────────────
     CERITA ASLI (ST-001 s/d ST-017)
  ───────────────────────────────────────── */
  {
    id: "ST-001",
    title: "Kancil dan Buaya",
    sub: "Kecerdikan mengalahkan kekuatan",
    emoji: "🦌",
    color: "#f59e0b",
    diff: "Easy",
    dur: "5 mnt",
    tags: ["hewan", "kecerdikan"],
    scenes: [
      {
        bg: "forest",
        char: "kancil",
        mood: "happy",
        amb: "forest",
        tx: "Di tengah hutan belantara yang hijau dan rindang, hiduplah seekor Kancil kecil yang terkenal paling cerdik di antara semua binatang. Matanya selalu berbinar-binar penuh akal!",
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "thinking",
        amb: "forest",
        tx: 'Hari itu perut Kancil keroncongan. Ia mencium aroma buah-buahan segar yang harum dari seberang sungai. "Pasti rasanya manis sekali," pikirnya sambil menelan ludah.',
      },
      {
        bg: "river",
        char: "kancil",
        mood: "thinking",
        amb: "river",
        tx: "Tapi sungai itu lebar dan deras sekali. Di permukaan air yang berkilau, Kancil bisa melihat bayangan punggung hitam para Buaya yang mengintai di bawah permukaan. Bahaya mengancam!",
      },
      {
        bg: "river",
        char: "buaya",
        mood: "angry",
        amb: "river",
        tx: '"Hei Kancil kecil!" suara menggelegar memecah kesunyian. Kepala Buaya muncul dari air, memperlihatkan deretan gigi tajamnya. "Berani-beraninya kamu mendekati sungaiku! Pergi sebelum aku makan kamu!"',
      },
      {
        bg: "river",
        char: "kancil",
        mood: "clever",
        amb: "river",
        tx: 'Kancil tidak gentar sedikit pun. Otaknya berputar cepat. Tiba-tiba ia punya ide cemerlang! "Wahai Buaya yang terhormat, aku datang membawa pesan penting dari Raja Hutan. Beliau ingin menghitung jumlah kalian untuk memberikan hadiah!"',
      },
      {
        bg: "river",
        char: "buaya",
        mood: "neutral",
        amb: "river",
        tx: 'Para Buaya saling pandang dengan serakah. "Hadiah?! Benarkah?" Tanpa berpikir panjang, mereka berbaris rapi membentang dari tepi ke tepi sungai, punggung mereka berderet seperti batu loncatan.',
      },
      {
        bg: "river",
        char: "kancil",
        mood: "happy",
        amb: "river",
        tx: 'Kancil melompat riang dari punggung satu Buaya ke Buaya lainnya! "Satu... dua... tiga... empat..." Ia menghitung sambil tertawa dalam hati. Kakinya tetap kering, tubuhnya tetap selamat!',
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "laugh",
        amb: "forest",
        tx: 'Setelah tiba di seberang dengan selamat, Kancil berbalik dan berteriak, "Terima kasih Buaya! Tapi sejujurnya, tidak ada hadiah dari Raja Hutan. Hanya kecerdikanku yang membantuku menyeberang!" Ia pun berlari sambil tertawa terbahak-bahak.',
        end: true,
        moral:
          "Kecerdikan dan keberanian lebih kuat daripada kekuatan fisik. Otak yang cerdas adalah senjata terbaik!",
      },
    ],
  },
  {
    id: "ST-002",
    title: "Timun Mas",
    sub: "Keberanian seorang gadis melawan raksasa",
    emoji: "🥒",
    color: "#22c55e",
    diff: "Medium",
    dur: "6 mnt",
    tags: ["keberanian", "magic"],
    scenes: [
      {
        bg: "village",
        char: "ibu",
        mood: "sad",
        amb: "village",
        tx: "Di sebuah desa yang tenang, tinggal seorang ibu yang hatinya selalu rindu. Setiap pagi ia duduk di depan rumahnya yang sunyi, memandang rumput yang dibasahi embun pagi. Ia sangat mendambakan seorang anak.",
      },
      {
        bg: "forest",
        char: "raksasa",
        mood: "neutral",
        amb: "forest",
        tx: 'Suatu malam yang mencekam, muncul seorang Raksasa yang tingginya menyentuh langit. Tanah bergetar saat ia melangkah. "Aku akan memberimu anak dari biji timun ajaib ini," suaranya menggelegar, "tapi saat ia berusia 17 tahun... ia harus menjadi milikku!"',
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Dari biji timun yang ditanam dengan penuh cinta, tumbuh seorang bayi mungil yang cantik jelita. Sang ibu menamainya Timun Mas. Ia tumbuh menjadi gadis yang riang, baik hati, dan selalu mengisi rumah dengan tawa.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "worried",
        amb: "village",
        tx: 'Hari ulang tahun ke-17 Timun Mas pun tiba. Sang ibu yang cemas segera pergi menemui petapa sakti. "Tolong selamatkan anakku!" Petapa itu memberikan empat kantong kecil berisi biji timun, jarum, garam, dan terasi ajaib.',
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "scared",
        amb: "village",
        tx: 'Raksasa datang mengguncang bumi! "Mana anakmu?!" Dengan berlinang air mata, sang ibu memeluk Timun Mas erat-erat. "Larilah Nak, gunakan kantong-kantong ini. Ibu selalu mencintaimu!" Timun Mas pun berlari sekencang angin!',
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "brave",
        amb: "forest",
        tx: "Timun Mas melempar biji timun ke belakangnya — BRAK! Seketika tumbuhlah hutan timun yang sangat lebat dan panjang. Namun Raksasa dengan mudah menerjangnya sambil mengaum marah!",
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "brave",
        amb: "rain",
        tx: "Timun Mas melempar jarum — KRAK! Hutan bambu berduri setinggi menara muncul tiba-tiba. Ia melempar garam — SPLOOSH! Lautan bergelombang menghalangi jalan. Lalu terasi — BLUUB! Lautan lumpur mendidih menggelegak dahsyat!",
      },
      {
        bg: "forest",
        char: "raksasa",
        mood: "defeated",
        amb: "rain",
        tx: "Raksasa yang jahat itu tersedot masuk ke dalam lumpur mendidih yang berputar seperti pusaran. Ia mengaum kesakitan, lalu perlahan tenggelam dan lenyap selamanya. Hutan kembali sunyi dan damai.",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Timun Mas berlari kembali ke desa dan langsung masuk ke pelukan hangat ibunya yang sudah menunggu dengan cemas. Mereka berdua menangis bahagia, berpelukan sangat erat. Keberanian Timun Mas telah menyelamatkan segalanya.",
        end: true,
        moral:
          "Kasih sayang orang tua adalah kekuatan terbesar. Dengan keberanian dan doa, tidak ada rintangan yang tidak bisa diatasi.",
      },
    ],
  },
  {
    id: "ST-003",
    title: "Sangkuriang",
    sub: "Asal-usul Gunung Tangkuban Perahu",
    emoji: "🌋",
    color: "#ef4444",
    diff: "Medium",
    dur: "6 mnt",
    tags: ["legenda"],
    scenes: [
      {
        bg: "forest",
        char: "dayang",
        mood: "happy",
        amb: "forest",
        tx: "Di tanah Sunda yang indah berhias bukit dan sungai jernih, hiduplah Dayang Sumbi, putri yang cantik jelita. Setiap hari ia menenun kain di tepi hutan sambil menikmati kicauan burung dan semilir angin.",
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "surprised",
        amb: "forest",
        tx: "Bertahun-tahun berlalu. Suatu hari datang pemuda yang sangat gagah dan tampan bernama Sangkuriang dari arah hutan. Ia jatuh hati dalam sekejap pada Dayang Sumbi yang tampak masih muda belia. Tapi ada rahasia besar yang tersembunyi...",
      },
      {
        bg: "village",
        char: "dayang",
        mood: "shocked",
        amb: "village",
        tx: 'Saat memeriksa rambut Sangkuriang, Dayang Sumbi menemukan sebuah bekas luka di kepalanya. Jantungnya berhenti sedetik. "Ya Tuhan... ini anakku yang pergi dulu!" Ia harus segera menggagalkan rencana pernikahan ini!',
      },
      {
        bg: "night",
        char: "dayang",
        mood: "clever",
        amb: "night",
        tx: 'Dayang Sumbi berpikir keras. Lalu dengan tenang ia berkata, "Baiklah Sangkuriang. Aku mau menikahimu, asalkan kamu bisa membuat sebuah danau besar dan sebuah perahu raksasa... hanya dalam satu malam saja."',
      },
      {
        bg: "night",
        char: "pemuda",
        mood: "working",
        amb: "night",
        tx: "Sangkuriang menyanggupi! Ia bersemedi memanggil makhluk-makhluk gaib dari seluruh penjuru hutan. Ribuan jin bekerja keras di bawah sinar bulan. Pohon-pohon tumbang, tanah bergetar, air mengalir deras. Hampir selesai!",
      },
      {
        bg: "night",
        char: "ibu",
        mood: "worried",
        amb: "night",
        tx: "Dayang Sumbi panik melihat pekerjaan Sangkuriang hampir rampung menjelang subuh! Ia segera membangunkan para gadis desa untuk menumbuk padi beramai-ramai dan menyalakan api unggun besar di ufuk timur, menipu langit seolah fajar telah tiba.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "angry",
        amb: "village",
        tx: "Ayam-ayam berkokok riuh! Para jin yang ketakutan langsung kabur meninggalkan pekerjaan mereka. Sangkuriang terdiam kaku, lalu meledak dalam amarah yang luar biasa saat menyadari tipu muslihat Dayang Sumbi.",
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "angry",
        amb: "forest",
        tx: "Dalam amarah yang memuncak, Sangkuriang menendang perahu besar yang hampir selesai itu dengan sekuat tenaga. BLAAMMM! Perahu itu melayang tinggi dan jatuh terbalik, menghujam bumi menjadi sebuah gunung besar.",
        end: true,
        moral:
          "Gunung Tangkuban Perahu yang kita lihat hari ini adalah warisan sejarah yang indah. Setiap gunung menyimpan cerita yang menakjubkan!",
      },
    ],
  },
  {
    id: "ST-004",
    title: "Bawang Merah & Bawang Putih",
    sub: "Kebaikan selalu berbuah kebaikan",
    emoji: "🧅",
    color: "#a855f7",
    diff: "Easy",
    dur: "5 mnt",
    tags: ["kebaikan", "keluarga"],
    scenes: [
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Di desa yang subur, hiduplah dua saudara tiri yang sangat berbeda. Bawang Putih selalu bangun pagi, menyapu halaman, dan membantu tetangga dengan senyum tulus. Sementara Bawang Merah masih tidur sambil bermimpi tentang emas.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "angry",
        amb: "village",
        tx: 'Ibu tiri dan Bawang Merah suka memerintah Bawang Putih seenaknya. "Cuci baju! Masak nasi! Bersihkan kandang!" Tapi Bawang Putih tidak pernah mengeluh. Ia mengerjakannya sambil bersenandung pelan.',
      },
      {
        bg: "river",
        char: "timunsmas",
        mood: "sad",
        amb: "river",
        tx: "Saat mencuci di sungai, kain Bawang Putih terseret arus dan hanyut. Ia mengikutinya jauh ke hilir, sampai menemukan sebuah gubuk tua di tepi sungai. Seorang nenek yang sangat tua duduk di sana, tersenyum ramah.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "happy",
        amb: "village",
        tx: '"Maukah kamu membantuku membersihkan rumah?" tanya nenek lembut. Bawang Putih langsung mengerjakan segalanya dengan bersemangat — menyapu, mengepel, memasak. Nenek sangat senang dan terkesan dengan ketulusan gadis itu.',
      },
      {
        bg: "river",
        char: "timunsmas",
        mood: "surprised",
        amb: "village",
        tx: '"Pilihkan satu hadiah," kata nenek sambil menunjuk dua labu besar dan kecil. Bawang Putih dengan rendah hati memilih yang kecil. Di rumah, saat dibelah, labu kecil itu berisi tumpukan emas, permata, dan kain sutra yang indah!',
      },
      {
        bg: "river",
        char: "buaya",
        mood: "neutral",
        amb: "river",
        tx: "Bawang Merah yang sangat iri langsung menghanyutkan kainnya sendiri. Ia berlari ke rumah nenek tua itu, tapi bekerja dengan setengah hati, sering mengeluh, dan selalu cemberut. Nenek hanya menggeleng pelan melihat sikapnya.",
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "angry",
        amb: "village",
        tx: "Bawang Merah dengan tamak langsung merampas labu yang paling besar! Ia berlari pulang sambil membayangkan kekayaan yang akan didapat. Namun saat labu itu dibelah di rumah... keluarlah ular, kalajengking, dan lebah yang langsung menyerangnya!",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Bawang Merah dan ibunya berlari ketakutan. Setelah tenang, mereka datang memohon maaf pada Bawang Putih dengan tulus. Bawang Putih memaafkan mereka dengan lapang dada, dan mereka pun akhirnya hidup rukun bersama.",
        end: true,
        moral:
          "Kebaikan hati dan kerendahan hati selalu membawa berkah. Keserakahan dan iri hati hanya mendatangkan kesulitan.",
      },
    ],
  },
  {
    id: "ST-005",
    title: "Malin Kundang",
    sub: "Pentingnya menghormati orang tua",
    emoji: "⛵",
    color: "#0ea5e9",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["keluarga", "hormat"],
    scenes: [
      {
        bg: "sea",
        char: "ibu",
        mood: "happy",
        amb: "sea",
        tx: "Di tepi pantai yang berbatu-batu, hiduplah seorang ibu dan anak lelaki bernama Malin Kundang. Mereka sangat miskin, namun selalu bahagia bersama. Sang ibu bekerja keras menangkap ikan setiap hari untuk menghidupi Malin.",
      },
      {
        bg: "sea",
        char: "pemuda",
        mood: "happy",
        amb: "sea",
        tx: 'Saat Malin beranjak dewasa, ia berpamitan untuk merantau mencari keberuntungan. "Ibu, tunggu aku pulang membawa emas!" Dengan perahu pedagang kaya, ia berlayar mengarungi lautan luas yang berombak.',
      },
      {
        bg: "sea",
        char: "pemuda",
        mood: "happy",
        amb: "sea",
        tx: "Bertahun-tahun berlalu. Malin berhasil menjadi saudagar yang sangat kaya. Ia menikah dengan putri bangsawan yang cantik. Kapal-kapalnya berlayar di berbagai lautan, membawa rempah dan emas. Ia melupakan desa kecilnya.",
      },
      {
        bg: "sea",
        char: "ibu",
        mood: "happy",
        amb: "sea",
        tx: 'Kabar kepulangan Malin sampai ke desa. Sang ibu yang sudah menua segera berlari ke pantai dengan kaki gemetar. Air matanya mengalir melihat kapal mewah berlabuh. "Malin! Anakku! Ibu sudah rindu sekali!"',
      },
      {
        bg: "sea",
        char: "pemuda",
        mood: "angry",
        amb: "sea",
        tx: 'Malin berdiri tegak di dek kapal yang megah, memandang ke bawah. Istrinya yang anggun berdiri di sampingnya. Malin merasa sangat malu. "Pergi kamu, wanita tua! Aku tidak mengenalmu! Aku tidak punya ibu sepertimu!" Kata-kata itu menghantam lebih keras dari ombak.',
      },
      {
        bg: "rain",
        char: "ibu",
        mood: "sad",
        amb: "rain",
        tx: "Sang ibu berdiri mematung. Air matanya bercampur dengan rintik hujan yang mulai turun. Hatinya yang hancur perlahan membara menjadi doa. Dengan suara yang gemetar ia mengangkat tangannya ke langit yang mulai menghitam...",
      },
      {
        bg: "rain",
        char: "pemuda",
        mood: "scared",
        amb: "rain",
        tx: 'Badai datang tiba-tiba! Petir menyambar-nyambar, ombak setinggi gunung menghantam kapal Malin. Malin berlutut gemetar ketakutan. "Ibu, ampunkan aku!" Tapi suaranya tenggelam dalam auman badai yang semakin ganas.',
        end: true,
        moral:
          "Hormati orang tuamu dengan sepenuh hati. Kasih ibu tidak ternilai harganya. Jangan pernah menyakiti hati mereka yang telah membesarkanmu.",
      },
    ],
  },
  {
    id: "ST-006",
    title: "Si Kera dan Buaya",
    sub: "Kecerdasan mengalahkan pengkhianatan",
    emoji: "🐒",
    color: "#f97316",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["hewan", "kecerdikan"],
    scenes: [
      {
        bg: "forest",
        char: "kancil",
        mood: "happy",
        amb: "forest",
        tx: "Di pohon ara yang tinggi di tepi sungai, tinggal seekor Kera yang lincah. Ia punya sahabat karib seekor Buaya besar. Setiap hari Kera dengan senang hati melempar buah-buahan manis ke mulut Buaya yang menunggu di bawah.",
      },
      {
        bg: "river",
        char: "buaya",
        mood: "neutral",
        amb: "river",
        tx: 'Istri Buaya jatuh sakit parah. Tabib berkata dengan serius, "Satu-satunya obatnya adalah hati Kera segar. Tanpa itu, istrimu tidak bisa sembuh." Buaya terdiam lama, menatap punggung sahabatnya dengan perasaan bersalah.',
      },
      {
        bg: "river",
        char: "buaya",
        mood: "neutral",
        amb: "river",
        tx: '"Kera, ayo ikut aku! Istriku ingin bertemu denganmu," bujuk Buaya. Kera melompat gembira ke punggung sahabatnya. Buaya berenang pelan menuju tengah sungai yang dalam. Arus di sini sangat deras...',
      },
      {
        bg: "river",
        char: "buaya",
        mood: "angry",
        amb: "river",
        tx: 'Di tengah sungai yang dalam, Buaya berhenti. Dengan nada berat ia berkata, "Maafkan aku Kera... tapi aku membutuhkan hatimu untuk menyembuhkan istriku." Kera terdiam sesaat. Jantungnya berdegup kencang. Tapi otaknya berputar sangat cepat!',
      },
      {
        bg: "river",
        char: "kancil",
        mood: "clever",
        amb: "river",
        tx: '"Aduh, mengapa kamu tidak bilang dari tadi?!" seru Kera sambil menepuk dahinya pura-pura. "Hatiku tertinggal di pohon ara tadi! Cepat kembalilah ke tepi, aku ambilkan hatiku!" Buaya yang polos langsung berbalik tanpa curiga.',
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "laugh",
        amb: "forest",
        tx: 'Begitu punggung Buaya menyentuh tepi sungai, Kera melompat setinggi-tingginya ke dahan pohon yang aman! Dari atas ia berteriak, "Bodohnya kamu Buaya! Apakah ada makhluk yang bisa meninggalkan hatinya di pohon? Kau telah mengkhianati persahabatan kita!"',
        end: true,
        moral:
          "Kecerdasan bisa menyelamatkan nyawa. Mengkhianati persahabatan sejati adalah kesalahan yang sangat menyedihkan.",
      },
    ],
  },
  {
    id: "ST-007",
    title: "Putri Tangguk",
    sub: "Bersyukur atas rezeki yang ada",
    emoji: "🌾",
    color: "#84cc16",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["kebaikan", "syukur"],
    scenes: [
      {
        bg: "village",
        char: "ibu",
        mood: "happy",
        amb: "village",
        tx: "Di desa yang hijau subur, Putri Tangguk terkenal sebagai petani paling beruntung. Sawahnya yang kecil selalu menghasilkan padi berlimpah — cukup untuk dimakan, dijual, dan diberikan ke tetangga. Semua orang kagum dengan keberkahannya.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "angry",
        amb: "village",
        tx: 'Namun anehnya, Putri Tangguk tidak pernah merasa cukup. Setiap hari ia mengeluh, "Capek sekali harus panen terus! Lumbungku sudah terlalu penuh, pusing aku lihatnya!" Suatu hari yang naas, ia membuang nasi yang masih baik ke tanah dengan kesal.',
      },
      {
        bg: "forest",
        char: "dayang",
        mood: "sad",
        amb: "night",
        tx: 'Malam itu, Putri Tangguk bermimpi. Seorang wanita cantik bercahaya berdiri di depannya. "Akulah Dewi Padi. Aku telah memberkahi sawahmu dengan penuh kasih. Tapi kamu membuang rezekimu dengan sembarangan. Sangat menyakitkan hatiku."',
      },
      {
        bg: "village",
        char: "ibu",
        mood: "shocked",
        amb: "village",
        tx: "Putri Tangguk terbangun dengan jantung berdegup. Ia berlari ke sawah... kosong! Berlari ke lumbung... kosong! Semua padi, semua beras, lenyap tanpa jejak. Ia jatuh berlutut dan menangis sejadi-jadinya.",
        end: true,
        moral:
          "Bersyukur adalah kunci kebahagiaan sejati. Hargai setiap rezeki yang kamu miliki, sekecil apapun itu, karena rezeki bisa pergi seketika.",
      },
    ],
  },
  {
    id: "ST-008",
    title: "Roro Jonggrang",
    sub: "Legenda Candi Prambanan yang megah",
    emoji: "🏛️",
    color: "#ec4899",
    diff: "Medium",
    dur: "6 mnt",
    tags: ["legenda"],
    scenes: [
      {
        bg: "village",
        char: "dayang",
        mood: "happy",
        amb: "village",
        tx: "Di Kerajaan Prambanan yang megah berdiri Roro Jonggrang, putri mahkota yang kecantikannya bagaikan rembulan. Rambut hitamnya panjang terurai, matanya berbinar seperti bintang. Seluruh negeri terpesona padanya.",
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "neutral",
        amb: "village",
        tx: "Dari kerajaan seberang datanglah Bandung Bondowoso, pangeran sakti mandraguna yang bisa menggerakkan batu dengan pikirannya. Ia langsung jatuh hati dan melamar Roro Jonggrang dengan upacara yang sangat mewah.",
      },
      {
        bg: "village",
        char: "dayang",
        mood: "clever",
        amb: "village",
        tx: 'Roro Jonggrang tidak mau dipaksa menikah. Ia berpikir keras mencari cara untuk menolak tanpa membuat perang. Tiba-tiba muncul ide. "Baiklah Bandung, aku mau menjadi istrimu... tapi dengan satu syarat yang harus kamu penuhi dulu."',
      },
      {
        bg: "night",
        char: "raksasa",
        mood: "neutral",
        amb: "night",
        tx: '"Bangunkan aku seribu candi yang megah dalam satu malam!" tantang Roro Jonggrang. Bandung Bondowoso menutup matanya, bersemedi. Tanah berguncang. Dari segala penjuru datanglah ribuan jin yang siap bekerja. Pekerjaan dimulai!',
      },
      {
        bg: "night",
        char: "ibu",
        mood: "worried",
        amb: "night",
        tx: 'Roro Jonggrang menghitung dengan jantung berdebar. Candi ke-900, ke-950, ke-990... hampir subuh! Candi ke-999 mau selesai! Ia berlari membangunkan seluruh gadis desa. "Cepat, tumbuk padi! Nyalakan api besar di timur! Sekarang!"',
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "angry",
        amb: "village",
        tx: "Langit di timur memerah seolah fajar. Ayam-ayam berkokok riuh! Para jin panik dan berhamburan pergi meninggalkan pekerjaan. Candi ke-1000 tidak selesai. Bandung Bondowoso berjalan mendekat dengan langkah berat dan mata yang memerah.",
      },
      {
        bg: "village",
        char: "dayang",
        mood: "shocked",
        amb: "village",
        tx: '"Roro Jonggrang! Kamu yang membunyikan fajar palsu itu!" tuduh Bandung dengan suara mengguncang tanah. "Karena kamu curang, maka jadilah kamu arca batu! Kamu akan melengkapi candi-candiku sebagai yang ke-1000!" Seketika tubuh Roro Jonggrang membatu.',
        end: true,
        moral:
          "Candi Prambanan yang indah itu menyimpan kisah ini. Kejujuran selalu lebih baik daripada kecurangan, seberapapun sulitnya.",
      },
    ],
  },
  {
    id: "ST-009",
    title: "Lutung Kasarung",
    sub: "Kebaikan hati membuahkan keajaiban",
    emoji: "🐒",
    color: "#78716c",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["kebaikan", "magic"],
    scenes: [
      {
        bg: "forest",
        char: "dayang",
        mood: "sad",
        amb: "forest",
        tx: 'Purbasari, putri kerajaan yang paling baik hati, dibuang ke hutan gelap oleh kakaknya yang jahat karena fitnah. Sendirian di antara pohon-pohon besar, ia duduk menangis pelan. "Mungkin ini takdirku," bisiknya.',
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "happy",
        amb: "forest",
        tx: "Namun ia tidak sendirian lama. Seekor lutung hitam berbulu lebat muncul dari balik semak. Dengan gerakan lembut, ia meletakkan buah-buahan segar di depan Purbasari. Setiap hari ia setia menjaga sang putri dari bahaya hutan.",
      },
      {
        bg: "forest",
        char: "dayang",
        mood: "happy",
        amb: "forest",
        tx: "Purbasari mulai sayang pada Lutung Kasarung. Ia bercerita padanya, bernyanyi untuknya, dan memperlakukannya seperti sahabat terbaik. Ia tidak pernah memandang rendah si lutung berbulu hitam itu walau sedetik pun.",
      },
      {
        bg: "night",
        char: "pemuda",
        mood: "surprised",
        amb: "night",
        tx: 'Malam bulan purnama yang indah. Sinar perak membasahi hutan. Tiba-tiba Lutung Kasarung bercahaya! Bulu-bulunya rontok, berganti dengan sosok pangeran tampan berwibawa. "Aku Guru Minda dari kahyangan yang dikutuk. Kamu telah membebaskanku dengan ketulusanmu."',
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Sang pangeran membawa Purbasari kembali ke kerajaan dengan penuh kemuliaan. Kakak yang jahat pun menerima ganjaran atas perbuatannya. Purbasari dan Guru Minda hidup bahagia, dan hutan pun kembali senyap dalam kedamaian.",
        end: true,
        moral:
          "Kebaikan hati yang tulus punya kekuatan ajaib. Perlakukan semua makhluk dengan kasih, karena kita tidak pernah tahu siapa yang ada di balik penampilannya.",
      },
    ],
  },
  {
    id: "ST-010",
    title: "Si Pitung",
    sub: "Pahlawan rakyat Betawi yang pemberani",
    emoji: "🦸",
    color: "#14b8a6",
    diff: "Medium",
    dur: "4 mnt",
    tags: ["keberanian", "kebaikan"],
    scenes: [
      {
        bg: "village",
        char: "pemuda",
        mood: "brave",
        amb: "village",
        tx: "Di kampung Betawi yang ramai di tepi Batavia, lahir dan tumbuh seorang pemuda bernama Pitung. Setiap fajar ia sudah bangun untuk mengaji, dan setiap hari ia berlatih silat di bawah bimbingan gurunya yang bijak.",
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "angry",
        amb: "village",
        tx: "Namun kampungnya ditindas. Para tuan tanah Belanda memungut pajak yang sangat berat. Petani yang tidak mampu membayar akan diusir dari tanahnya sendiri. Warga menangis kelaparan, tapi tidak ada yang berani melawan.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "brave",
        amb: "village",
        tx: "Pitung tidak tahan melihat penderitaan itu. Dengan ilmu silatnya yang tinggi dan keberanian yang membara, ia mulai menggerebek gudang-gudang tuan tanah kaya di malam hari, lalu membagikan hasilnya ke rakyat yang kelaparan.",
      },
      {
        bg: "night",
        char: "pemuda",
        mood: "brave",
        amb: "night",
        tx: "Kompeni Belanda mengerahkan pasukan untuk menangkap Pitung. Tapi rakyat selalu melindunginya — menyembunyikannya di rumah, memberinya makan, memperingatkannya dari bahaya. Pitung selalu selangkah lebih cepat dari para pengejarnya.",
        end: true,
        moral:
          "Keberanian untuk membela yang lemah adalah tindakan mulia. Gunakan kemampuan dan kekuatanmu untuk kebaikan orang banyak.",
      },
    ],
  },
  {
    id: "ST-011",
    title: "Gadis dan Cermin Ajaib",
    sub: "Kecantikan sejati ada di dalam hati",
    emoji: "🪞",
    color: "#6366f1",
    diff: "Easy",
    dur: "3 mnt",
    tags: ["kebaikan"],
    scenes: [
      {
        bg: "village",
        char: "timunsmas",
        mood: "sad",
        amb: "village",
        tx: 'Sari adalah gadis desa yang selalu diremehkan teman-temannya. "Bajumu jelek! Rambutmu tidak rapi!" ejek mereka. Namun Sari tetap tersenyum. Ia percaya ada sesuatu yang lebih penting dari penampilan luar.',
      },
      {
        bg: "forest",
        char: "dayang",
        mood: "neutral",
        amb: "forest",
        tx: 'Suatu hari di pinggir hutan, Sari menemukan cermin kuno yang bercahaya lembut. Rasa penasaran mendorongnya untuk bertanya, "Cermin ajaib, apa sebenarnya kecantikan sejati itu?" Cermin itu menjawab dengan cahaya yang hangat, "Kecantikan sejati bersinar dari hati yang baik dan tulus."',
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Sari menyimpan jawaban itu di hatinya. Ia semakin rajin membantu tetangga yang susah, merawat orang tua yang sakit, dan selalu menyambut semua orang dengan senyum yang tulus. Perlahan, sinar kebaikannya mulai dirasakan semua orang.",
        end: true,
        moral:
          "Kecantikan sejati bukan tentang penampilan fisik, melainkan tentang kebaikan dan ketulusan hati yang bersinar dari dalam.",
      },
    ],
  },
  {
    id: "ST-012",
    title: "Anak Gembala dan Serigala",
    sub: "Akibat berbohong kepada orang yang mempercayaimu",
    emoji: "🐑",
    color: "#64748b",
    diff: "Easy",
    dur: "3 mnt",
    tags: ["kejujuran", "hewan"],
    scenes: [
      {
        bg: "forest",
        char: "kancil",
        mood: "happy",
        amb: "forest",
        tx: 'Di padang rumput yang luas dan hijau, Budi setiap hari menggembalakan puluhan domba milik keluarganya. Hari-harinya terasa sangat membosankan. Ia ingin membuat sesuatu yang "menarik" terjadi.',
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "laugh",
        amb: "forest",
        tx: 'Tiba-tiba Budi berteriak sekeras-kerasnya, "SERIGALA! SERIGALA ADA DI SINI!" Para petani berlari dari sawah membawa cangkul dan sabit. Tapi tidak ada apa-apa. Budi tertawa terpingkal-pingkal melihat mereka kelelahan. "Hahaha, kalian tertipu!"',
      },
      {
        bg: "forest",
        char: "raksasa",
        mood: "angry",
        amb: "forest",
        tx: 'Esok harinya, serigala berbulu abu-abu yang lapar sungguh-sungguh datang mengintai kawanan domba! Budi berlari dan berteriak sambil melambaikan tangan, "TOLONG! SERIGALA! SERIGALA SUNGGUHAN!" Tapi tidak ada seorangpun yang datang.',
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "sad",
        amb: "forest",
        tx: 'Domba-domba Budi berpencar ketakutan dan berhasil dicuri serigala. Budi duduk di tanah sambil menangis pilu. Pak tua tetangganya datang dan berkata dengan lembut, "Budi, inilah akibatnya jika kita bermain-main dengan kepercayaan orang lain."',
        end: true,
        moral:
          "Kejujuran adalah pondasi kepercayaan. Sekali kamu berbohong, kepercayaan orang lain padamu akan sulit pulih kembali.",
      },
    ],
  },
  {
    id: "ST-013",
    title: "Legenda Danau Toba",
    sub: "Asal-usul danau vulkanik terbesar dunia",
    emoji: "🏞️",
    color: "#06b6d4",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["legenda"],
    scenes: [
      {
        bg: "river",
        char: "pemuda",
        mood: "happy",
        amb: "river",
        tx: "Di lembah hijau yang dikelilingi bukit-bukit menjulang, Toba seorang pemuda sederhana menjalani hidupnya sebagai nelayan. Suatu sore yang cerah, jalanya menangkap sesuatu yang berkilau emas di dalam air jernih.",
      },
      {
        bg: "river",
        char: "dayang",
        mood: "surprised",
        amb: "river",
        tx: 'Ikan itu bergerak aneh di tangannya... lalu POOF! Berubah menjadi seorang gadis cantik bercahaya dengan rambut basah tergerai. "Namaku Putri. Kamu telah menyelamatkanku. Aku akan menikahimu, tapi ingat satu janji penting: jangan pernah ceritakan asal-usulku kepada siapapun."',
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Mereka menikah dan dikaruniai anak lelaki yang nakal bernama Samosir. Kehidupan mereka bahagia. Toba bekerja keras di sawah setiap hari, dan Putri mengurus rumah dengan penuh kasih. Desa pun menjadi makmur dan tentram.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "angry",
        amb: "village",
        tx: 'Suatu siang Toba pulang dari sawah dalam keadaan sangat lelah dan lapar. Samosir belum mengantarkan bekalnya. Ketika ia temukan anaknya sedang bermain, kemarahannya meledak. "Dasar anak ikan! Tidak berguna!" Kata-kata itu terucap begitu saja.',
      },
      {
        bg: "rain",
        char: "dayang",
        mood: "sad",
        amb: "rain",
        tx: 'Langit mendadak gelap. Angin kencang berhembus. Putri muncul dengan wajah sedih namun tenang. "Kamu telah melanggar janjimu, Toba. Aku harus kembali." Hujan lebat turun, tidak berhenti. Air terus naik dan naik...',
      },
      {
        bg: "sea",
        char: "pemuda",
        mood: "sad",
        amb: "river",
        tx: "Lembah itu perlahan tergenang air dan berubah menjadi danau yang sangat luas dan dalam. Samosir berlari ke bukit yang kini menjadi pulau di tengah danau. Danau indah itu kita kenal sekarang sebagai Danau Toba, dan pulau di tengahnya adalah Pulau Samosir.",
        end: true,
        moral:
          "Sebuah janji adalah ikatan suci. Jaga perkataanmu, karena kata-kata yang terucap tidak bisa ditarik kembali.",
      },
    ],
  },
  {
    id: "ST-014",
    title: "Kelinci dan Kura-Kura",
    sub: "Ketekunan selalu mengalahkan kesombongan",
    emoji: "🐢",
    color: "#10b981",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["hewan", "ketekunan"],
    scenes: [
      {
        bg: "forest",
        char: "kancil",
        mood: "happy",
        amb: "forest",
        tx: 'Di hutan yang rindang, Kelinci adalah bintangnya. Ia bisa berlari lebih cepat dari semua binatang dan sangat suka pamer. "Lihat aku!" teriaknya sambil berlari berputar-putar. "Tak ada yang bisa menandingi kecepatanku!"',
      },
      {
        bg: "forest",
        char: "buaya",
        mood: "neutral",
        amb: "forest",
        tx: 'Kura-kura yang sedang berjalan lambat di dekatnya berkata dengan tenang, "Kamu memang cepat Kelinci. Tapi bagaimana kalau kita berlomba saja? Dari pohon beringin ini sampai ke batu besar di ujung hutan." Semua binatang terdiam kaget.',
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "laugh",
        amb: "forest",
        tx: 'Kelinci tertawa terpingkal-pingkal sampai perutnya sakit. Binatang-binatang lain juga ikut tertawa. Tapi Kura-kura tidak bergeming. Wajahnya tetap tenang dan penuh keyakinan. "Aku serius, Kelinci. Maukah kamu?"',
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "thinking",
        amb: "forest",
        tx: 'Lomba pun dimulai! Kelinci melesat secepat kilat, meninggalkan Kura-kura jauh di belakang. Setelah setengah perjalanan, Kelinci berhenti dan merebahkan diri di bawah pohon yang teduh. "Kura-kura pasti masih sangat jauh di belakang. Aku tidur sebentar saja..."',
      },
      {
        bg: "forest",
        char: "buaya",
        mood: "happy",
        amb: "forest",
        tx: "Kura-kura terus melangkah. Satu langkah, dua langkah, pelan tapi pasti. Saat melewati Kelinci yang mendengkur keras, ia tidak berhenti. Ia terus berjalan, terus berjalan, sampai akhirnya... batu besar di ujung hutan terlihat di depannya!",
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "shocked",
        amb: "forest",
        tx: "KRIUK! Suara ranting patah membangunkan Kelinci. Ia membuka mata... batu besar itu masih jauh! Ia berlari sekencang mungkin, tapi ketika tiba di garis finish, Kura-kura sudah duduk di sana dengan senyum tenangnya. Semua binatang bersorak keras!",
        end: true,
        moral:
          "Ketekunan dan konsistensi tanpa henti akan selalu mengalahkan bakat yang tidak diimbangi kerja keras dan kerendahan hati.",
      },
    ],
  },
  {
    id: "ST-015",
    title: "Ande-Ande Lumut",
    sub: "Menjaga hati diri adalah kekuatan sejati",
    emoji: "💚",
    color: "#4ade80",
    diff: "Medium",
    dur: "4 mnt",
    tags: ["keluarga", "kebaikan"],
    scenes: [
      {
        bg: "village",
        char: "timunsmas",
        mood: "sad",
        amb: "village",
        tx: "Kleting Kuning menjalani hidupnya dengan sabar di bawah perintah ibu dan saudara-saudara tirinya. Setiap pagi ia mengambil air, memasak, mencuci — sementara mereka masih bermain dan bermalas-malasan. Tapi senyumnya tak pernah padam.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "happy",
        amb: "village",
        tx: "Kabar angin berhembus ke seluruh desa: Pangeran Ande-Ande Lumut yang tampan, bijaksana, dan kaya sedang mencari istri yang tepat! Kleting Biru, Kleting Hijau, dan Kleting Merah — saudara-saudara tirinya — langsung bersemangat berhias diri.",
      },
      {
        bg: "river",
        char: "buaya",
        mood: "neutral",
        amb: "river",
        tx: "Untuk sampai ke tempat sang pangeran, semua orang harus menyeberangi sungai yang dijaga Yuyu Kangkang, kepiting raksasa yang jahat. Ia mau menyeberangkan para gadis, tapi dengan syarat yang sangat merendahkan martabat mereka.",
      },
      {
        bg: "river",
        char: "timunsmas",
        mood: "brave",
        amb: "river",
        tx: 'Saudara-saudara tiri Kleting Kuning memilih menerima syarat itu demi bisa bertemu pangeran. Tapi saat tiba giliran Kleting Kuning, ia dengan tegas menggeleng. "Aku lebih baik tidak bertemu pangeran manapun daripada harus merendahkan diriku!" Ia menyeberang sendiri dengan susah payah.',
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "happy",
        amb: "village",
        tx: 'Di hadapan sang pangeran, Kleting Kuning berdiri dengan pakaian basah dan kusut. Namun Ande-Ande Lumut berdiri dan memilih tepat di depannya. "Hanya kamu yang datang dengan hati yang terjaga bersih. Itu jauh lebih berharga dari seribu mahkota emas."',
        end: true,
        moral:
          "Menjaga harga diri dan kehormatan adalah tindakan terkuat yang bisa dilakukan seseorang. Orang yang tepat akan selalu menghargainya.",
      },
    ],
  },
  {
    id: "ST-016",
    title: "Cahaya yang Mengubah Kegelapan",
    sub: "Kebaikan tulus menembus hati yang paling keras",
    emoji: "🌟",
    color: "#f59e0b",
    diff: "Easy",
    dur: "3 mnt",
    tags: ["kebaikan"],
    scenes: [
      {
        bg: "night",
        char: "raksasa",
        mood: "angry",
        amb: "night",
        tx: "Di ujung hutan yang paling gelap, tinggal seorang penyihir tua yang ditakuti semua orang. Dulu ia baik, tapi bertahun-tahun hidup sendirian dan dikucilkan membuat hatinya mengeras seperti batu karang.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "brave",
        amb: "village",
        tx: 'Mpu Bahula, murid muda yang bijak, memilih mendatangi si penyihir sendirian. Ia tidak membawa senjata, hanya membawa makanan dan senyum tulus. "Bolehkah aku belajar darimu, tuan? Aku percaya kamu punya banyak kebijaksanaan untuk dibagikan."',
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "neutral",
        amb: "village",
        tx: "Si penyihir mencurigai Mpu Bahula. Tapi pemuda itu datang setiap hari, merawatnya saat sakit, mendengarkan ceritanya dengan sabar. Perlahan, seperti es yang mencair terkena hangat matahari, hati si penyihir mulai melunak.",
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "happy",
        amb: "forest",
        tx: "Kegelapan yang pernah menutup hati si penyihir perlahan berubah menjadi cahaya. Ia mulai menggunakan ilmunya untuk menyembuhkan dan membantu. Desa pun berubah dari ketakutan menjadi penuh kasih. Satu kebaikan telah mengubah segalanya.",
        end: true,
        moral:
          "Kebaikan yang tulus, kesabaran, dan kepercayaan adalah senjata paling kuat untuk mengubah kegelapan menjadi cahaya.",
      },
    ],
  },
  {
    id: "ST-017",
    title: "Surat untuk Ibu",
    sub: "Tidak ada kata terlambat untuk pulang",
    emoji: "💌",
    color: "#f43f5e",
    diff: "Easy",
    dur: "3 mnt",
    tags: ["keluarga"],
    scenes: [
      {
        bg: "village",
        char: "pemuda",
        mood: "sad",
        amb: "village",
        tx: "Raka merantau ke kota besar dengan mimpi yang menggebu. Bulan berlalu menjadi tahun. Pekerjaan, teman baru, dan kehidupan kota yang sibuk membuatnya lupa. Lupa untuk menelepon. Lupa untuk menulis. Lupa untuk pulang.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "sad",
        amb: "village",
        tx: "Di desa, sang ibu berdiri di depan pintu setiap sore menjelang matahari tenggelam. Matanya selalu menatap jalan setapak yang membelah ladang. Di mejanya selalu ada makanan kesukaan Raka yang masih hangat, siapa tahu ia tiba-tiba pulang.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "sad",
        amb: "village",
        tx: "Suatu malam, Raka melihat foto lama di dompetnya — ia dan ibunya saat ia masih kecil. Air matanya tidak bisa ditahan. Ia segera mengambil kertas dan menulis surat panjang berisi semua penyesalannya, lalu membeli tiket bus untuk pulang.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "happy",
        amb: "village",
        tx: 'Saat Raka turun dari bus, ibunya sudah berdiri di ujung jalan dengan mata yang berkaca-kaca. Tidak ada kata marah. Hanya pelukan hangat yang sangat panjang. "Pulang saja, Nak. Rumah selalu menunggumu." Raka menangis dalam pelukan yang paling hangat di dunia.',
        end: true,
        moral:
          "Kasih ibu tidak pernah habis dan tidak pernah menyimpan dendam. Jangan biarkan kesibukan membuatmu lupa pulang kepada orang-orang yang menyayangimu.",
      },
    ],
  },

  /* ─────────────────────────────────────────
     CERITA BARU — LOKAL (ST-018 s/d ST-024)
  ───────────────────────────────────────── */
  {
    id: "ST-018",
    title: "Keong Mas",
    sub: "Putri cantik yang tersembunyi dalam cangkang emas",
    emoji: "🐚",
    color: "#eab308",
    diff: "Easy",
    dur: "5 mnt",
    tags: ["legenda", "magic"],
    scenes: [
      {
        bg: "village",
        char: "ibu",
        mood: "sad",
        amb: "village",
        tx: "Di sebuah desa kecil, hiduplah seorang janda tua yang sangat miskin bernama Mbok Rondo. Setiap hari ia bekerja keras di sawah, namun hasilnya tidak pernah cukup. Hatinya selalu terasa sepi dan sunyi.",
      },
      {
        bg: "river",
        char: "ibu",
        mood: "surprised",
        amb: "river",
        tx: "Suatu pagi di tepi sungai yang jernih, Mbok Rondo menemukan sebuah keong yang cangkangnya berkilau seperti emas murni. Belum pernah ia melihat keong seindah itu. Dengan hati-hati ia membawanya pulang dan menempatkannya di dalam tempayan air.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "surprised",
        amb: "village",
        tx: "Hal ajaib pun terjadi! Setiap kali Mbok Rondo pergi ke ladang dan pulang ke rumah, selalu sudah tersedia nasi yang harum, lauk yang lezat, dan rumah yang bersih rapi. Siapa gerangan yang melakukan semua ini?",
      },
      {
        bg: "village",
        char: "dayang",
        mood: "surprised",
        amb: "village",
        tx: 'Mbok Rondo diam-diam mengintip dari balik pintu. Ia terperangah melihat seorang gadis cantik bercahaya keluar dari keong emas itu dan mulai memasak! "Siapa kamu, Nak?" tanyanya dengan suara bergetar penuh keharuan.',
      },
      {
        bg: "village",
        char: "dayang",
        mood: "sad",
        amb: "village",
        tx: '"Namaku Dewi Chandrakirana, Nek. Aku dikutuk oleh penyihir jahat menjadi keong emas karena menolak lamarannya. Aku terpaksa bersembunyi di dalam cangkang ini." Air mata mengalir di pipi gadis cantik itu.',
      },
      {
        bg: "village",
        char: "dayang",
        mood: "happy",
        amb: "village",
        tx: "Mbok Rondo merawat Dewi Chandrakirana dengan penuh kasih. Kabar pun sampai ke telinga pangeran yang sejak lama mencari sang putri. Sang pangeran datang membawa obat pemutus kutukan. Keong emas pun pecah, dan Dewi Chandrakirana bebas selamanya!",
        end: true,
        moral:
          "Kebaikan hati selalu dibalas dengan keajaiban. Menolong orang yang membutuhkan adalah perbuatan paling mulia.",
      },
    ],
  },
  {
    id: "ST-019",
    title: "Cindelaras",
    sub: "Ayam jago ajaib dan keberanian seorang anak",
    emoji: "🐓",
    color: "#dc2626",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["legenda", "keberanian"],
    scenes: [
      {
        bg: "forest",
        char: "ibu",
        mood: "sad",
        amb: "forest",
        tx: "Permaisuri Raja Raden Putra difitnah oleh selir yang jahat dan diusir ke hutan belantara. Di hutan yang sunyi itu, ia melahirkan seorang bayi lelaki yang tampan dan diberi nama Cindelaras. Mereka hidup sederhana namun penuh kasih.",
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "happy",
        amb: "forest",
        tx: "Cindelaras tumbuh menjadi anak yang luar biasa. Hewan-hewan hutan menjadi sahabatnya. Suatu hari seekor rajawali memberinya sebutir telur ajaib. Dari telur itu menetas seekor ayam jantan yang berbeda dari ayam biasa — berkokok dengan kata-kata!",
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "surprised",
        amb: "forest",
        tx: '"Kukuruyuk... Tuanku Cindelaras, rumahnya di tengah hutan, beratap daun kelapa, ayahnya Raja Raden Putra!" Cindelaras terkejut mendengar rahasia besar itu terungkap melalui kokokan ajaib sang ayam jantan.',
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "brave",
        amb: "village",
        tx: "Dengan berani, Cindelaras berjalan jauh menuju istana. Ia menantang ayam jago milik raja dalam sebuah pertandingan adu ayam. Seluruh istana menyaksikan. Pertaruhan diajukan: jika ayam Cindelaras kalah, ia akan dihukum. Jika menang, setengah kerajaan menjadi miliknya.",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Ayam jago Cindelaras bertarung dengan gagah berani! Dalam sekejap ia mengalahkan ayam raja yang terkenal kuat itu. Raja terpesona dan memanggil Cindelaras. Saat melihat wajah anak itu, jantung raja berdegup — ia begitu mirip dengan wajah sang permaisuri.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "happy",
        amb: "village",
        tx: "Raja segera memerintahkan pencarian sang permaisuri. Mereka berpelukan dengan berlinang air mata bahagia. Selir jahat yang memfitnah pun menerima hukumannya. Cindelaras resmi diakui sebagai putra mahkota, dan keluarga yang terpisah akhirnya bersatu kembali.",
        end: true,
        moral:
          "Kebenaran tidak bisa disembunyikan selamanya. Kesabaran dan keberanian akan selalu membawa keadilan pada akhirnya.",
      },
    ],
  },
  {
    id: "ST-020",
    title: "Jaka Tarub",
    sub: "Bidadari yang turun ke bumi",
    emoji: "🪄",
    color: "#8b5cf6",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["legenda", "magic"],
    scenes: [
      {
        bg: "forest",
        char: "pemuda",
        mood: "happy",
        amb: "forest",
        tx: "Di tepi hutan yang lebat, hiduplah seorang pemuda bernama Jaka Tarub yang tampan dan gemar berburu. Suatu hari ia mendengar suara tawa ceria dari arah telaga tersembunyi di balik pohon-pohon besar.",
      },
      {
        bg: "river",
        char: "dayang",
        mood: "happy",
        amb: "river",
        tx: "Jaka Tarub mengintip dari balik semak dan terpesona melihat tujuh bidadari cantik sedang mandi di telaga bercahaya. Pakaian bersayap mereka tersimpan rapi di tepi telaga. Tanpa berpikir panjang, ia mengambil satu selendang milik bidadari bungsu.",
      },
      {
        bg: "river",
        char: "dayang",
        mood: "sad",
        amb: "river",
        tx: 'Para bidadari bergegas kembali ke langit. Namun Nawang Wulan, bidadari bungsu, tidak bisa ikut — selendangnya raib! "Tanpa selendang ini aku tidak bisa terbang," tangisnya sendirian di tepi telaga yang mulai gelap.',
      },
      {
        bg: "village",
        char: "dayang",
        mood: "neutral",
        amb: "village",
        tx: "Jaka Tarub muncul dan menawarkan pertolongan. Nawang Wulan terpaksa tinggal dan akhirnya menikah dengannya. Mereka hidup bahagia, dikaruniai seorang putri cantik. Namun Nawang Wulan selalu terlihat memandang langit dengan tatapan yang penuh kerinduan.",
      },
      {
        bg: "village",
        char: "dayang",
        mood: "sad",
        amb: "village",
        tx: "Suatu hari, saat mengambil beras dari lumbung, Nawang Wulan menemukan selendangnya yang tersembunyi di antara tumpukan padi. Air matanya mengalir deras. Ia tahu sudah saatnya kembali ke tempat asalnya, ke kahyangan yang selama ini ia rindukan.",
      },
      {
        bg: "night",
        char: "dayang",
        mood: "sad",
        amb: "night",
        tx: 'Nawang Wulan memeluk putri kecilnya erat-erat, lalu berpamitan pada Jaka Tarub. "Jaga anak kita baik-baik. Jika ia merindukanku, ajak ia ke ladang saat bulan purnama — aku akan melihatnya dari langit." Perlahan ia naik ke langit, menjadi bintang yang paling terang.',
        end: true,
        moral:
          "Kejujuran dan kepercayaan adalah fondasi sebuah hubungan. Menyembunyikan kebenaran hanya akan mendatangkan kesedihan di kemudian hari.",
      },
    ],
  },
  {
    id: "ST-021",
    title: "Asal Usul Kota Surabaya",
    sub: "Pertarungan epik Sura si Hiu dan Baya si Buaya",
    emoji: "🦈",
    color: "#0ea5e9",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["legenda"],
    scenes: [
      {
        bg: "sea",
        char: "buaya",
        mood: "angry",
        amb: "sea",
        tx: "Di lautan yang luas, dua makhluk paling kuat bersaing memperebutkan wilayah kekuasaan. Sura adalah hiu raksasa yang menguasai lautan, sementara Baya adalah buaya besar yang ingin menguasai daratan. Keduanya selalu saling iri dan berselisih.",
      },
      {
        bg: "river",
        char: "buaya",
        mood: "angry",
        amb: "river",
        tx: "Sura mulai menerobos wilayah sungai — daerah kekuasaan Baya! Baya pun murka bukan kepalang. Mereka sepakat untuk bertarung habis-habisan demi menentukan siapa yang paling berkuasa.",
      },
      {
        bg: "river",
        char: "raksasa",
        mood: "angry",
        amb: "river",
        tx: "Pertarungan dahsyat pun terjadi! Air sungai bergolak, tanah di tepi sungai ikut berguncang. Gigitan dan tamparan saling dilancarkan. Pertarungan berlangsung sangat lama hingga keduanya sama-sama kelelahan dan penuh luka.",
      },
      {
        bg: "river",
        char: "buaya",
        mood: "defeated",
        amb: "river",
        tx: 'Akhirnya mereka berdamai dengan sebuah perjanjian yang tegas: "Sura berkuasa di air, Baya berkuasa di darat!" Namun diam-diam Sura kembali melanggar perjanjian dengan memasuki sungai yang merupakan wilayah Baya.',
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Pertarungan terakhir dimenangkan oleh Baya yang berhasil menggigit ekor Sura. Sura mundur ke lautan selamanya. Sejak saat itu, wilayah pertarungan mereka menjadi kota yang dinamai Surabaya — dari kata Sura (hiu) dan Baya (buaya). Patung keduanya berdiri megah sebagai lambang kota!",
        end: true,
        moral:
          "Menghormati perjanjian dan batas adalah kunci perdamaian. Keserakahan hanya akan mendatangkan konflik yang tidak perlu.",
      },
    ],
  },
  {
    id: "ST-022",
    title: "Putri Mandalika",
    sub: "Pengorbanan cinta demi perdamaian rakyat",
    emoji: "🌊",
    color: "#06b6d4",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["legenda", "keberanian"],
    scenes: [
      {
        bg: "village",
        char: "dayang",
        mood: "happy",
        amb: "village",
        tx: "Di kerajaan Tonjang Beru di Pulau Lombok yang indah, hiduplah Putri Mandalika yang kecantikannya tiada tanding. Hatinya selembut bunga, tutur katanya selalu menyejukkan. Seluruh rakyat mencintainya dengan sepenuh hati.",
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "angry",
        amb: "village",
        tx: "Namun kecantikannya mendatangkan masalah besar. Berpuluh pangeran dari berbagai kerajaan melamar sekaligus. Mereka tidak mau mengalah. Perselisihan memanas dan hampir meledak menjadi perang saudara yang akan memakan ribuan nyawa.",
      },
      {
        bg: "village",
        char: "dayang",
        mood: "sad",
        amb: "village",
        tx: 'Putri Mandalika merenungkan nasib rakyatnya yang akan menderita jika perang pecah. Dengan hati yang berat namun penuh keteguhan, ia membuat keputusan yang tidak pernah terbayangkan siapapun. "Tidak akan ada yang menang, dan tidak ada yang kalah."',
      },
      {
        bg: "sea",
        char: "dayang",
        mood: "brave",
        amb: "sea",
        tx: "Di bawah langit malam bertaburan bintang, Putri Mandalika berdiri di tepi tebing menghadap lautan. Dengan suara yang jernih ia berkata, \"Aku mencintai kalian semua, rakyatku. Karena itulah aku memilih untuk menjadi milik semua orang, bukan hanya satu orang saja.\"",
      },
      {
        bg: "sea",
        char: "dayang",
        mood: "happy",
        amb: "sea",
        tx: "Putri Mandalika melompat ke dalam ombak yang bergemuruh. Dari tempat ia jatuh, muncul ribuan cacing warna-warni yang disebut Nyale, memberi makan seluruh rakyat yang lapar. Setiap tahun, rakyat Lombok merayakan Festival Nyale untuk mengenang pengorbanannya.",
        end: true,
        moral:
          "Pengorbanan tulus demi orang banyak adalah bentuk cinta tertinggi. Ada keberanian yang jauh lebih besar dari bertempur, yaitu berkorban demi perdamaian.",
      },
    ],
  },
  {
    id: "ST-023",
    title: "Si Kabayan",
    sub: "Kelucuan si pemalas yang selalu berhasil",
    emoji: "😄",
    color: "#f59e0b",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["humor", "keluarga"],
    scenes: [
      {
        bg: "village",
        char: "pemuda",
        mood: "happy",
        amb: "village",
        tx: "Si Kabayan adalah pemuda Sunda yang paling terkenal di desanya. Bukan karena gagah atau kaya, melainkan karena ia adalah orang paling malas di seluruh kampung! Namun anehnya, ia selalu berhasil keluar dari masalah dengan cara-cara yang paling tidak terduga.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "angry",
        amb: "village",
        tx: 'Suatu pagi, Ambu (ibunya) membangunkan Si Kabayan dengan keras, "Kabayan! Pergi ke pasar, belikan ikan! Jangan lupa bawa pulang dengan benar!" Si Kabayan mengantuk mengangguk, lalu berjalan santai ke pasar dengan mata setengah tertutup.',
      },
      {
        bg: "river",
        char: "pemuda",
        mood: "thinking",
        amb: "river",
        tx: 'Si Kabayan membeli ikan segar di pasar. Di perjalanan pulang melewati sungai yang dingin, ia berpikir keras. "Ikan ini hidup di air," pikirnya sambil menguap. "Tentu lebih nyaman kalau dibawa berenang!" Ia pun melepaskan ikan-ikan itu ke sungai dan menuntunnya dengan tali tak kasatmata.',
      },
      {
        bg: "village",
        char: "ibu",
        mood: "angry",
        amb: "village",
        tx: '"Mana ikannya, Kabayan?!" teriak Ambu. "Sudah kubawa pulang, Bu. Tapi mereka lebih suka jalan sendiri lewat sungai," jawab Kabayan polos sambil garuk-garuk kepala. Ambu hampir pingsan. Tapi apa daya, anaknya selalu punya penjelasan yang sangat masuk akal baginya sendiri.',
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "laugh",
        amb: "village",
        tx: "Di balik kelucuan dan kemalasannya, Si Kabayan selalu punya hati yang baik. Saat tetangga membutuhkan bantuan, ia yang pertama datang meskipun harus menyeret diri dari tempat tidurnya. Rakyat sekampung pun tertawa dan mencintai si Kabayan yang unik.",
        end: true,
        moral:
          "Hidup bisa dijalani dengan penuh tawa dan kegembiraan. Jadilah dirimu sendiri, dan selalu gunakan hatimu untuk berbuat baik kepada sesama.",
      },
    ],
  },
  {
    id: "ST-024",
    title: "Nyi Roro Kidul",
    sub: "Legenda Ratu Penguasa Lautan Selatan",
    emoji: "🌊",
    color: "#0f766e",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["legenda", "magic"],
    scenes: [
      {
        bg: "village",
        char: "dayang",
        mood: "sad",
        amb: "village",
        tx: "Putri Kadita adalah putri raja yang cantik jelita di Tanah Sunda. Namun ibu tirinya yang cemburu menyuruh dukun jahat untuk menyihirnya — tubuh sang putri yang cantik tiba-tiba dipenuhi penyakit yang memalukan.",
      },
      {
        bg: "forest",
        char: "dayang",
        mood: "sad",
        amb: "forest",
        tx: "Raja dengan berat hati mengusir putrinya dari istana. Putri Kadita berjalan tanpa tujuan berhari-hari lamanya, menembus hutan lebat, melewati padang yang luas, hingga sampai di tepi pantai selatan yang berombak besar dan menakutkan.",
      },
      {
        bg: "sea",
        char: "dayang",
        mood: "sad",
        amb: "sea",
        tx: "Sebuah suara gaib yang lembut memanggilnya dari balik ombak. \"Masuklah ke dalam lautanku, dan kamu akan sembuh serta menjadi ratu yang perkasa.\" Tanpa ragu, Putri Kadita melangkah ke dalam ombak besar yang menggulung menghampirinya.",
      },
      {
        bg: "sea",
        char: "dayang",
        mood: "happy",
        amb: "sea",
        tx: "Ajaib! Saat ia muncul dari lautan, semua penyakitnya lenyap. Ia tampak lebih cantik dari sebelumnya, bercahaya seperti bulan purnama di atas laut. Jubah hijau kehijauan pun menyelimuti tubuhnya — ia telah berubah menjadi penguasa lautan selatan yang perkasa.",
      },
      {
        bg: "sea",
        char: "dayang",
        mood: "neutral",
        amb: "sea",
        tx: "Sejak saat itu, Nyi Roro Kidul menjadi Ratu Penguasa Laut Selatan yang disegani semua orang. Para nelayan menghormatinya dan selalu berdoa meminta keselamatannya sebelum melaut. Lautan selatan yang ganas pun dijaganya dengan bijaksana.",
        end: true,
        moral:
          "Kesabaran menghadapi cobaan dan ketabahan hati akan mengubah penderitaan menjadi kekuatan. Setiap badai pasti berlalu bagi mereka yang bertahan.",
      },
    ],
  },

  /* ─────────────────────────────────────────
     CERITA MANCANEGARA (ST-025 s/d ST-038)
  ───────────────────────────────────────── */
  {
    id: "ST-025",
    title: "Cinderella",
    sub: "Kebaikan hati selalu menemukan jalannya",
    emoji: "👠",
    color: "#60a5fa",
    diff: "Easy",
    dur: "5 mnt",
    tags: ["kebaikan", "mancanegara"],
    scenes: [
      {
        bg: "village",
        char: "timunsmas",
        mood: "sad",
        amb: "village",
        tx: "Cinderella hidup bersama ibu tiri dan dua saudara tirinya yang jahat. Setiap hari ia harus mengerjakan semua pekerjaan rumah sendirian — mencuci, memasak, menyapu — sementara mereka bersenang-senang. Namun Cinderella tidak pernah kehilangan kebaikan hatinya.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "angry",
        amb: "village",
        tx: 'Undangan datang dari istana — ada pesta dansa besar untuk sang pangeran! Ibu tiri dan saudara-saudara tiri Cinderella berhias semeriah mungkin. "Kamu tinggal di rumah dan bersihkan lantai!" usir ibu tiri sambil tertawa jahat. Cinderella menelan kesedihan sendirian.',
      },
      {
        bg: "night",
        char: "dayang",
        mood: "surprised",
        amb: "night",
        tx: "Tiba-tiba cahaya keemasan bersinar di dapur yang sunyi. Ibu Peri Cinderella muncul dengan tongkat ajaibnya! Labu berubah menjadi kereta emas, tikus menjadi kuda putih, dan pakaian usang Cinderella berubah menjadi gaun paling indah yang pernah ada. Sepatu kristal bersinar di kakinya.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "happy",
        amb: "village",
        tx: "Di pesta istana, semua orang terpesona pada Cinderella yang cantik mempesona. Sang pangeran langsung mengajaknya berdansa. Saat musik mengalun lembut, waktu seolah berhenti — hanya ada mereka berdua di tengah ruangan yang berkilau gemerlap.",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "scared",
        amb: "village",
        tx: "BONG! BONG! Jam berdentang dua belas kali! Cinderella berlari sekencang mungkin menuruni tangga istana. Satu sepatu kristalnya terlepas dan tertinggal. Sang pangeran memungutnya dan bersumpah akan mencari sang gadis misterius ke seluruh negeri.",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Keesokan harinya, sang pangeran berkeliling mengujicoba sepatu kristal ke setiap gadis. Saat tiba di rumah Cinderella, sepatu itu pas sempurna di kakinya! Sang pangeran berlutut, melamarnya, dan Cinderella pun hidup bahagia selamanya — dengan hati yang tetap penuh kebaikan.",
        end: true,
        moral:
          "Kebaikan hati dan kesabaran akan selalu berbuah kebahagiaan. Tidak ada kegelapan yang cukup pekat untuk memadamkan cahaya orang yang berhati baik.",
      },
    ],
  },
  {
    id: "ST-026",
    title: "Putri Salju",
    sub: "Hati yang baik mengalahkan sihir yang jahat",
    emoji: "🍎",
    color: "#ef4444",
    diff: "Easy",
    dur: "5 mnt",
    tags: ["kebaikan", "mancanegara"],
    scenes: [
      {
        bg: "village",
        char: "dayang",
        mood: "happy",
        amb: "village",
        tx: "Di kerajaan yang diselimuti salju, hiduplah Putri Salju yang berkulit seputih salju, berambut sehitam malam, dan berbibirkan semerah buah delima. Ia adalah gadis paling cantik sekaligus paling baik hati di seluruh kerajaan.",
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "angry",
        amb: "village",
        tx: 'Namun ratu tirinya yang jahat memiliki cermin ajaib yang bisa berbicara. Setiap hari ia bertanya, "Cermin, siapakah yang paling cantik?" Dan cermin selalu menjawab, "Putri Salju, Yang Mulia." Ratu membakar dalam amarah dan cemburu yang gelap.',
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "scared",
        amb: "forest",
        tx: "Ratu memerintahkan pemburu untuk membawa Putri Salju ke hutan dan membunuhnya. Namun si pemburu tidak tega. Ia melepaskan sang putri dan membiarkannya lari ke dalam hutan yang gelap dan sunyi. Putri Salju berlari ketakutan sendirian.",
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "surprised",
        amb: "forest",
        tx: "Di balik pepohonan besar Putri Salju menemukan sebuah gubuk mungil yang rapi dan bersih. Di dalamnya ada tujuh tempat tidur kecil yang tertata rapi. Itulah rumah tujuh kurcaci yang ramah dan menyambutnya dengan hangat.",
      },
      {
        bg: "forest",
        char: "ibu",
        mood: "angry",
        amb: "forest",
        tx: "Ratu yang tahu Putri Salju masih hidup menyamar menjadi nenek tua penjual apel. Ia datang ke gubuk kurcaci membawa apel merah yang cantik namun telah diracuni. Putri Salju yang baik hati menerimanya dan menggigit apel itu... ia pun jatuh tertidur pulas.",
      },
      {
        bg: "forest",
        char: "dayang",
        mood: "happy",
        amb: "forest",
        tx: "Pangeran dari kerajaan seberang menemukan Putri Salju yang tertidur cantik. Jatuh hati dalam sekejap, ia mencium keningnya dengan lembut. Ajaib! Putri Salju pun terbangun! Ratu jahat mendapat hukuman setimpal, dan Putri Salju hidup bahagia selamanya.",
        end: true,
        moral:
          "Kebaikan dan kejujuran tidak bisa dikalahkan oleh kejahatan. Selalu berhati-hati terhadap orang asing yang menawarkan hadiah dengan terlalu mudah.",
      },
    ],
  },
  {
    id: "ST-027",
    title: "Hansel dan Gretel",
    sub: "Keberanian dua saudara mengalahkan penyihir",
    emoji: "🏠",
    color: "#f97316",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["keberanian", "keluarga", "mancanegara"],
    scenes: [
      {
        bg: "forest",
        char: "timunsmas",
        mood: "sad",
        amb: "forest",
        tx: "Hansel dan Gretel adalah kakak beradik yang hidup miskin di tepi hutan. Suatu malam mereka mendengar ibu tiri berencana meninggalkan mereka di hutan agar bisa makan sendiri. Keduanya ketakutan tapi tidak menyerah.",
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "clever",
        amb: "forest",
        tx: "Hansel yang cerdik mengumpulkan batu-batu putih kecil dan menebarkannya di sepanjang jalan saat mereka dibawa ke hutan keesokan harinya. Ketika ditinggal sendirian, mereka mengikuti jejak batu-batu yang berkilau di bawah cahaya bulan dan berhasil pulang!",
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "scared",
        amb: "forest",
        tx: "Namun malam berikutnya mereka dibawa lagi, kali ini Hansel hanya bisa menebarkan remah roti. Sayangnya, burung-burung memakan semua remah itu. Mereka pun benar-benar tersesat jauh di dalam hutan yang gelap dan menakutkan.",
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "angry",
        amb: "forest",
        tx: 'Tiba-tiba mereka menemukan rumah yang terbuat dari roti, kue, dan permen! Mereka mulai memakan dinding rumah itu dengan lapar. "Siapa yang menggigit rumahku?!" sebuah suara parau terdengar. Penyihir tua yang menyeramkan membuka pintu dan menangkap mereka.',
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "brave",
        amb: "village",
        tx: "Penyihir itu mengurung Hansel untuk digemukkan. Gretel berpura-pura bodoh saat penyihir menyuruhnya mengecek oven. Ketika penyihir menunduk melihat ke dalam oven, Gretel mendorongnya dengan sekuat tenaga — BLAM! Penyihir itu masuk ke dalam oven!",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Hansel bebas! Mereka menemukan kotak berisi emas dan permata di rumah penyihir. Dengan gembira mereka pulang menemui ayah mereka yang sudah menangis merindukannya. Ibu tiri yang jahat sudah pergi, dan mereka hidup bahagia bersama.",
        end: true,
        moral:
          "Kecerdasan dan keberanian bersama-sama bisa mengalahkan bahaya. Jangan pernah menyerah meski situasi tampak sangat sulit, karena selalu ada jalan keluar bagi mereka yang berani berpikir.",
      },
    ],
  },
  {
    id: "ST-028",
    title: "Si Tudung Merah",
    sub: "Jangan berbicara dengan orang asing!",
    emoji: "🐺",
    color: "#dc2626",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["hewan", "keluarga", "mancanegara"],
    scenes: [
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Di desa yang ceria hiduplah seorang gadis kecil yang selalu memakai tudung berwarna merah. Suatu hari ibunya memberinya sekeranjang makanan lezat. \"Antarkan ini ke rumah Nenek yang sakit, tapi jangan lewat jalan memutar dan jangan bicara dengan orang asing!\"",
      },
      {
        bg: "forest",
        char: "raksasa",
        mood: "neutral",
        amb: "forest",
        tx: "Di tengah perjalanan melalui hutan, Si Tudung Merah bertemu seekor serigala besar berbulu abu-abu yang tersenyum manis. \"Hai gadis kecil, mau ke mana?\" Meskipun sedikit ragu, Si Tudung Merah menjawab dengan polos. Serigala itu punya rencana jahat!",
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "happy",
        amb: "forest",
        tx: "Serigala membujuk Si Tudung Merah untuk memetik bunga di padang yang jauh dari jalan utama. Sementara itu, serigala berlari kencang ke rumah Nenek, masuk, dan menelan Nenek! Ia pun berbaring di tempat tidur pura-pura menjadi sang Nenek.",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "surprised",
        amb: "village",
        tx: '"Nek, mengapa telingamu sangat besar?" — "Agar bisa mendengarmu lebih baik!" "Mengapa matamu sangat besar?" — "Agar bisa melihatmu lebih baik!" "Mengapa gigimu sangat besar?" — "Agar bisa MEMAKANMU!" Si Tudung Merah berteriak keras!',
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "brave",
        amb: "forest",
        tx: "Seorang pemburu yang lewat mendengar teriakan Si Tudung Merah dan langsung masuk membantu. Serigala itu berhasil dikalahkan, dan Nenek pun selamat. Si Tudung Merah berlari ke pelukan Neneknya yang hangat, berjanji tidak akan pernah lagi berbicara dengan orang asing.",
        end: true,
        moral:
          "Dengarkanlah pesan orang tua kita — itu adalah bentuk kasih sayang mereka. Jangan sembarangan berbicara dengan orang yang tidak kita kenal, karena tidak semua yang tersenyum punya niat baik.",
      },
    ],
  },
  {
    id: "ST-029",
    title: "Jack dan Pohon Kacang Ajaib",
    sub: "Keberanian di negeri raksasa di atas awan",
    emoji: "🌱",
    color: "#22c55e",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["keberanian", "mancanegara"],
    scenes: [
      {
        bg: "village",
        char: "pemuda",
        mood: "sad",
        amb: "village",
        tx: "Jack dan ibunya sangat miskin. Harta satu-satunya hanyalah sapi tua. Terpaksa, ibu menyuruh Jack menjual sapi itu ke pasar. Di perjalanan, Jack bertemu pedagang misterius yang menawarkan lima biji kacang ajaib sebagai pengganti sapi.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "angry",
        amb: "village",
        tx: 'Ibu Jack sangat marah melihat anaknya pulang dengan tangan kosong. "Lima biji kacang?! Apa yang bisa kita makan dari kacang?!" Ia melempar biji-biji itu keluar jendela dengan kesal. Jack tidur dengan perut kosong yang keroncongan.',
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "surprised",
        amb: "forest",
        tx: "Esok paginya, pohon kacang setinggi langit tumbuh di luar jendela! Batangnya besar, daunnya rimbun, tumbuh menembus awan. Jack memanjat tanpa pikir panjang, terus naik dan naik sampai ia tiba di sebuah istana raksasa di atas awan.",
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "angry",
        amb: "village",
        tx: 'Raksasa pemilik istana mengaum saat mencium bau Jack: "Fe fi fo fum! Aku mencium bau darah manusia!" Jack bersembunyi di balik peti emas dan menemukan angsa ajaib yang bisa bertelur emas. Ia mengambilnya dan berlari sekencang mungkin!',
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "brave",
        amb: "forest",
        tx: "Raksasa mengejar Jack menuruni pohon kacang! Jack yang lebih dulu sampai di bawah berteriak pada ibunya. Dengan sekuat tenaga Jack menebang pohon kacang itu. KRAK! Pohon itu roboh dan raksasa jatuh lenyap ke tanah.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "happy",
        amb: "village",
        tx: "Angsa ajaib bertelur emas setiap hari. Jack dan ibunya tidak lagi miskin — mereka hidup berkecukupan dan selalu bersyukur. Jack belajar bahwa keberanian yang bijaksana bisa mengubah nasib seseorang.",
        end: true,
        moral:
          "Keberanian dan kecerdasan bisa mengubah nasib. Namun selalu gunakan apa yang kamu dapatkan dengan bijak, dan jangan lupa berbagi dengan sesama.",
      },
    ],
  },
  {
    id: "ST-030",
    title: "Bebek Buruk Rupa",
    sub: "Setiap makhluk punya keindahannya sendiri",
    emoji: "🦢",
    color: "#7dd3fc",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["hewan", "mancanegara"],
    scenes: [
      {
        bg: "river",
        char: "timunsmas",
        mood: "sad",
        amb: "river",
        tx: "Di tepi kolam yang tenang, menetas sekelompok telur bebek. Semuanya menggemaskan kecuali satu — anak bebek yang satu ini berbeda. Tubuhnya besar, bulunya kusam abu-abu, dan jalannya tidak karuan. Semua orang di kolam mengejeknya.",
      },
      {
        bg: "river",
        char: "timunsmas",
        mood: "sad",
        amb: "river",
        tx: '"Pergi kamu, bebek jelek!" usir bebek-bebek lain. Bahkan saudara-saudaranya sendiri tidak mau bermain bersamanya. Setiap hari si bebek buruk rupa menyendiri di sudut kolam, menatap bayangannya di air yang tenang dengan sangat sedih.',
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "sad",
        amb: "night",
        tx: "Musim dingin yang kejam pun datang. Si bebek buruk rupa mengembara sendirian mencari kehangatan. Ia hampir membeku di atas danau yang mulai mengeras menjadi es. Seorang petani yang baik hati menemukannya dan membawanya ke dalam rumah yang hangat untuk pulih.",
      },
      {
        bg: "river",
        char: "timunsmas",
        mood: "surprised",
        amb: "river",
        tx: "Musim semi tiba membawa kehangatan. Si bebek buruk rupa tumbuh dan berubah. Saat ia mendekati kolam dan melihat bayangannya di air yang jernih, ia tidak percaya — yang terlihat bukan bebek jelek, melainkan seekor angsa yang anggun dan cantik!",
      },
      {
        bg: "river",
        char: "dayang",
        mood: "happy",
        amb: "river",
        tx: "Kawanan angsa putih di danau menyambutnya dengan riang. \"Bergabunglah bersama kami!\" Anak-anak yang bermain di tepi danau berseru, \"Lihat! Angsa baru yang paling cantik!\" Si bebek yang dulu direndahkan kini terbang anggun bersama kawanannya dengan penuh kebanggaan.",
        end: true,
        moral:
          "Jangan menilai seseorang dari penampilan luarnya. Setiap orang punya keistimewaan tersendiri yang akan terlihat pada waktunya. Bersabarlah dan percayalah pada dirimu sendiri.",
      },
    ],
  },
  {
    id: "ST-031",
    title: "Pinokio",
    sub: "Anak kayu yang ingin menjadi manusia sungguhan",
    emoji: "🪵",
    color: "#92400e",
    diff: "Easy",
    dur: "5 mnt",
    tags: ["kejujuran", "mancanegara"],
    scenes: [
      {
        bg: "village",
        char: "pemuda",
        mood: "happy",
        amb: "village",
        tx: "Di bengkel kayu yang nyaman, seorang tukang kayu tua bernama Geppetto mengukir sebuah boneka kayu dengan penuh cinta. Ia memberinya nama Pinokio. Malam itu, peri biru datang dan menghidupkan Pinokio. \"Jadilah anak yang baik, dan suatu hari kamu bisa menjadi anak sungguhan!\"",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Pinokio sangat gembira! Geppetto membekalinya dengan buku dan mengirimnya ke sekolah. Namun di tengah jalan, Pinokio tergoda oleh dua penipu yang mengajaknya ke teater boneka — sekolah pun terlupakan begitu saja.",
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "scared",
        amb: "night",
        tx: "Pinokio mulai berbohong. Setiap kali ia berbohong, hidungnya tumbuh semakin panjang! Peri biru datang bertanya kenapa ia tidak ke sekolah. \"Aku... aku sakit!\" bohong Pinokio — hidungnya langsung memanjang sampai mengenai dinding!",
      },
      {
        bg: "sea",
        char: "pemuda",
        mood: "scared",
        amb: "sea",
        tx: "Pinokio terus membuat masalah hingga akhirnya tertelan oleh paus raksasa bersama Geppetto yang sedang mencarinya! Di dalam perut paus yang gelap, Pinokio menangis menyesal. Ia pun membuat api besar sehingga paus bersin dan memuntahkan mereka berdua ke pantai.",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Pinokio berenang sekuat tenaga menyelamatkan Geppetto yang kelelahan. Peri biru tersenyum melihat ketulusan hati Pinokio. Malam itu, saat Pinokio tidur, ia berubah — menjadi anak manusia sungguhan! Geppetto menangis haru memeluk putranya yang kini hidup nyata.",
        end: true,
        moral:
          "Kejujuran adalah sifat yang paling penting. Kebohongan kecil selalu membawa masalah yang lebih besar. Beranikan dirimu untuk selalu berkata jujur!",
      },
    ],
  },
  {
    id: "ST-032",
    title: "Putri Duyung Kecil",
    sub: "Mimpi yang indah dan pengorbanan yang tulus",
    emoji: "🧜",
    color: "#06b6d4",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["magic", "mancanegara"],
    scenes: [
      {
        bg: "sea",
        char: "dayang",
        mood: "happy",
        amb: "sea",
        tx: "Jauh di dalam samudra yang biru, hiduplah Putri Duyung kecil yang cantik dan penuh rasa ingin tahu. Ia selalu mengintip ke permukaan laut, bermimpi tentang dunia manusia di atas. Koleksi benda-benda manusia tersimpan rapi di kamarnya yang indah.",
      },
      {
        bg: "sea",
        char: "dayang",
        mood: "surprised",
        amb: "sea",
        tx: "Saat muncul ke permukaan untuk pertama kalinya, Putri Duyung menyaksikan kapal yang indah dilanda badai. Seorang pangeran tampan jatuh ke laut. Tanpa pikir panjang, ia menyelamatkan pangeran itu dan membawanya ke pantai. Hatinya berdegup dengan perasaan yang belum pernah ia rasakan.",
      },
      {
        bg: "sea",
        char: "raksasa",
        mood: "neutral",
        amb: "sea",
        tx: "Putri Duyung mendatangi penyihir laut yang jahat. \"Aku ingin kaki manusia agar bisa bertemu sang pangeran!\" Penyihir itu setuju — dengan syarat: suaranya yang merdu sebagai bayarannya. Dan jika sang pangeran menikahi orang lain, ia akan menjadi buih laut.",
      },
      {
        bg: "village",
        char: "dayang",
        mood: "happy",
        amb: "village",
        tx: "Dengan kaki baru yang sakit setiap dilangkahkan, Putri Duyung menemukan sang pangeran. Mereka berteman akrab. Pangeran senang bersamanya meski tidak tahu bahwa gadis bisu ini adalah penyelamatnya. Putri Duyung bahagia, meski hatinya juga sering menangis diam-diam.",
      },
      {
        bg: "sea",
        char: "dayang",
        mood: "sad",
        amb: "sea",
        tx: "Pangeran menikahi putri dari negeri lain. Putri Duyung memandang dari kejauhan, hatinya hancur. Kakak-kakaknya datang membawa pisau ajaib — ia bisa diselamatkan jika bersedia menyakiti sang pangeran. Namun Putri Duyung menggeleng dengan lembut. Ia tidak sanggup menyakiti orang yang dicintainya.",
        end: true,
        moral:
          "Cinta yang sejati tidak memaksakan kehendak. Pengorbanan yang tulus, meski menyakitkan, adalah bukti cinta yang paling mulia dan indah.",
      },
    ],
  },
  {
    id: "ST-033",
    title: "Aladdin dan Lampu Ajaib",
    sub: "Kejujuran hati lebih berharga dari seribu keinginan",
    emoji: "🪔",
    color: "#f59e0b",
    diff: "Easy",
    dur: "5 mnt",
    tags: ["keberanian", "mancanegara"],
    scenes: [
      {
        bg: "village",
        char: "pemuda",
        mood: "happy",
        amb: "village",
        tx: "Di kota Arab yang sibuk dan ramai, hiduplah Aladdin, pemuda yatim piatu yang ceria namun miskin. Ia suka berlarian di antara lapak-lapak pasar, mencuri sedikit buah untuk dimakan. Hatinya baik, tapi hidupnya sangat sulit.",
      },
      {
        bg: "forest",
        char: "raksasa",
        mood: "neutral",
        amb: "night",
        tx: "Penyihir jahat menyamar menjadi paman baik dan membawa Aladdin ke gua ajaib. \"Ambilkan aku lampu tua dari dalam gua itu!\" Aladdin masuk dan menemukan tumpukan emas dan batu permata. Namun saat ingin keluar, penyihir mengkhianatinya dan mengurungnya di dalam!",
      },
      {
        bg: "night",
        char: "timunsmas",
        mood: "surprised",
        amb: "night",
        tx: "Aladdin tidak sengaja menggosok sebuah cincin dan WUUSSHHH! Roh cincin muncul! Ia mengantarkan Aladdin keluar dari gua. Di rumah, Aladdin menggosok lampu tua itu untuk dibersihkan — BOOOM! Roh lampu yang jauh lebih kuat muncul dengan menggelegar!",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "happy",
        amb: "village",
        tx: "Roh lampu yang baik hati mengabulkan tiga keinginan Aladdin. Dengan bijak, Aladdin meminta makanan untuk ibunya, pakaian yang layak, dan kesempatan untuk melamar Putri Jasmine yang cantik. Sang sultan terkesan dengan kebaikan dan ketulusan hati Aladdin.",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Penyihir jahat berusaha mencuri lampu, namun Aladdin mengalahkannya dengan kecerdikan. Keinginan terakhirnya bukan untuk dirinya sendiri — ia membebaskan roh lampu yang telah menjadi sahabatnya. Aladdin dan Jasmine pun hidup bahagia dengan hati yang lapang.",
        end: true,
        moral:
          "Gunakan anugerah dan kemampuanmu untuk kebaikan orang lain. Kekayaan sejati bukan berasal dari lampu ajaib, melainkan dari hati yang jujur dan penuh kebaikan.",
      },
    ],
  },
  {
    id: "ST-034",
    title: "Ali Baba dan Empat Puluh Penyamun",
    sub: "Kecerdasan mengalahkan kejahatan",
    emoji: "🏺",
    color: "#b45309",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["keberanian", "mancanegara"],
    scenes: [
      {
        bg: "forest",
        char: "pemuda",
        mood: "surprised",
        amb: "forest",
        tx: 'Ali Baba, pencari kayu yang miskin, sedang bekerja di hutan ketika melihat empat puluh perampok berkuda datang. Mereka berhenti di depan batu besar dan pemimpin mereka berteriak, "Sesama kawan, buka!" Batu itupun terbelah, membuka gua tersembunyi yang penuh emas berkilau!',
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "clever",
        amb: "forest",
        tx: 'Setelah para perampok pergi, Ali Baba mencoba mengucapkan kata ajaib itu sendiri. "Sesama kawan, buka!" Batu terbelah! Matanya membulat melihat tumpukan emas yang berkilau di dalam gua. Dengan hati-hati ia mengambil beberapa kantong emas dan pulang.',
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "angry",
        amb: "night",
        tx: "Pemimpin perampok mengetahui ada yang mencuri dari gudangnya! Ia menyuruh anak buahnya mencari Ali Baba. Mereka menemukan rumahnya dan merencanakan serangan malam — bersembunyi di dalam empat puluh guci besar minyak yang dibawa ke rumah Ali Baba.",
      },
      {
        bg: "village",
        char: "dayang",
        mood: "clever",
        amb: "night",
        tx: "Marjanah, pembantu Ali Baba yang cerdik, mencurigai guci-guci itu. Ia mengintip ke salah satu guci dan menemukan perampok yang bersembunyi! Dengan tenang ia merebus minyak dan menuangkannya ke setiap guci satu per satu. Ancaman itu berhasil dilenyapkan!",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Pemimpin perampok datang sendiri menyamar sebagai pedagang, namun Marjanah mengenalinya saat menari hiburan dan mengalahkannya. Ali Baba sangat berterima kasih. Emas dari gua digunakan untuk membantu orang-orang miskin di kota.",
        end: true,
        moral:
          "Kecerdasan dan keberanian bisa mengalahkan kekuatan yang jauh lebih besar. Selalu waspada dan gunakan pikiranmu dengan baik dalam menghadapi bahaya.",
      },
    ],
  },
  {
    id: "ST-035",
    title: "Semut dan Belalang",
    sub: "Kerja keras hari ini untuk hari esok yang lebih baik",
    emoji: "🐜",
    color: "#84cc16",
    diff: "Easy",
    dur: "3 mnt",
    tags: ["hewan", "mancanegara"],
    scenes: [
      {
        bg: "forest",
        char: "kancil",
        mood: "happy",
        amb: "forest",
        tx: "Di padang rumput yang hijau di musim panas yang cerah, si Belalang melompat riang dari bunga ke bunga. Ia bernyanyi keras-keras dan bermain sepanjang hari tanpa henti. Tidak ada satu pun kekhawatiran di kepalanya yang lompat-lompat itu.",
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "happy",
        amb: "forest",
        tx: "Di dekatnya, kawanan Semut bekerja keras tanpa kenal lelah. Mereka mengangkat makanan yang jauh lebih berat dari tubuh mereka sendiri, berbaris panjang menuju sarang. Keringat mengucur, kaki pegal, tapi mereka terus bekerja dengan penuh semangat dan tujuan.",
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "laugh",
        amb: "forest",
        tx: '"Hei Semut, mengapa kalian bekerja begitu keras di cuaca seindah ini?" ejek Belalang sambil bermalas-malasan. "Ayo bernyanyi dan bermain bersamaku!" Para semut menggeleng, "Kami sedang menyiapkan makanan untuk musim dingin. Kamu juga sebaiknya melakukan hal yang sama."',
      },
      {
        bg: "night",
        char: "kancil",
        mood: "sad",
        amb: "rain",
        tx: "Musim dingin yang kejam tiba! Angin berhembus sangat kencang dan makanan tidak ada lagi di ladang. Belalang yang kelaparan dan kedinginan berjalan tertatih-tatih mencari makan. Ia terdiam malu saat melewati sarang semut yang hangat dan penuh makanan yang cukup untuk berbulan-bulan.",
        end: true,
        moral:
          "Bekerja keras dan bersiap untuk masa depan adalah hal yang sangat penting. Jangan tunda pekerjaan untuk besok apa yang bisa dikerjakan hari ini. Musim panas tidak selamanya!",
      },
    ],
  },
  {
    id: "ST-036",
    title: "Singa dan Tikus Kecil",
    sub: "Tidak ada pertolongan yang terlalu kecil",
    emoji: "🦁",
    color: "#fbbf24",
    diff: "Easy",
    dur: "3 mnt",
    tags: ["hewan", "kebaikan", "mancanegara"],
    scenes: [
      {
        bg: "forest",
        char: "raksasa",
        mood: "angry",
        amb: "forest",
        tx: "Raja hutan, Singa yang perkasa, sedang tidur siang dengan nyenyak di bawah pohon rindang ketika seekor tikus kecil tidak sengaja berlari melintasi hidungnya. Singa terbangun dan menangkap si Tikus dengan cakarnya yang besar.",
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "scared",
        amb: "forest",
        tx: '"Maafkan aku, Raja! Tolong lepaskan aku!" pinta Tikus kecil dengan suara gemetar. "Suatu hari nanti, aku pasti bisa membalasmu dengan cara yang kamu tidak bayangkan!" Singa tertawa terbahak-bahak mendengar klaim si makhluk kecil itu, namun ia melepaskannya karena terhibur.',
      },
      {
        bg: "forest",
        char: "raksasa",
        mood: "scared",
        amb: "forest",
        tx: "Beberapa hari kemudian, Singa terjebak dalam jaring pemburu yang sangat kuat! Ia mengaum keras meminta tolong, namun tidak ada yang berani mendekati. Tikus kecil yang mendengar aumannya berlari secepat mungkin menuju Singa.",
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "happy",
        amb: "forest",
        tx: "Tanpa ragu, Tikus kecil mulai menggigit tali-tali jaring itu satu per satu dengan giginya yang tajam. PUTUS! PUTUS! PUTUS! Perlahan tapi pasti, jaring itu terlepas. Singa yang perkasa pun bebas! Matanya berkaca-kaca menatap sang penyelamat kecilnya.",
        end: true,
        moral:
          "Tidak ada kebaikan yang terlalu kecil dan tidak ada makhluk yang terlalu lemah untuk membantu. Balaslah kebaikan dengan kebaikan, karena pertolongan bisa datang dari tempat yang paling tidak kita duga.",
      },
    ],
  },
  {
    id: "ST-037",
    title: "Rapunzel",
    sub: "Kebebasan tidak bisa dikurung selamanya",
    emoji: "👩",
    color: "#f472b6",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["keberanian", "mancanegara"],
    scenes: [
      {
        bg: "forest",
        char: "dayang",
        mood: "sad",
        amb: "forest",
        tx: "Di dalam menara tinggi yang terpencil di tengah hutan, terkurung seorang gadis bernama Rapunzel. Rambutnya yang indah tumbuh sangat panjang, mengalir seperti sungai emas. Penyihir jahat yang mengurungnya datang setiap hari dengan berteriak, \"Rapunzel, turunkan rambutmu!\"",
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "surprised",
        amb: "forest",
        tx: "Seorang pangeran yang tersesat di hutan mendengar nyanyian merdu dari menara itu. Ia melihat penyihir memanjat rambut Rapunzel. Esok harinya, sang pangeran mencoba cara yang sama. \"Rapunzel, turunkan rambutmu!\" — dan rambut itu pun turun menyambut.",
      },
      {
        bg: "night",
        char: "dayang",
        mood: "happy",
        amb: "night",
        tx: "Pangeran dan Rapunzel menjadi sahabat, lalu perlahan tumbuh menjadi lebih dari sekedar sahabat. Mereka merencanakan pelarian bersama. Namun penyihir jahat mengetahuinya! Ia memotong rambut Rapunzel dan mengusirnya ke padang gersang yang jauh.",
      },
      {
        bg: "forest",
        char: "dayang",
        mood: "happy",
        amb: "forest",
        tx: "Pangeran mencari Rapunzel ke seluruh penjuru negeri. Akhirnya mereka bertemu kembali. Air mata bahagia Rapunzel jatuh ke mata sang pangeran yang terluka — dan matanya pun sembuh! Mereka berdua berjalan keluar dari hutan gelap menuju cahaya kebebasan.",
        end: true,
        moral:
          "Kebebasan adalah hak setiap manusia. Kasih sayang yang tulus bisa menembus tembok dan menara sekalipun. Selalu ada cahaya di ujung kegelapan bagi mereka yang tidak menyerah.",
      },
    ],
  },
  {
    id: "ST-038",
    title: "Putri dan Sang Pangeran Terkutuk",
    sub: "Cinta sejati melihat keindahan di dalam hati",
    emoji: "🌹",
    color: "#f43f5e",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["kebaikan", "mancanegara"],
    scenes: [
      {
        bg: "forest",
        char: "raksasa",
        mood: "angry",
        amb: "forest",
        tx: "Di dalam istana yang tertutup kabut, tinggal seorang pangeran yang dikutuk menjadi raksasa mengerikan karena sombong dan tidak baik hati. Ia hidup sendirian di antara benda-benda bernyawa yang juga terkena kutukan. Ia harus menemukan cinta sejati sebelum waktu habis.",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "surprised",
        amb: "village",
        tx: "Belle, gadis desa yang cerdas dan suka membaca, mendapati ayahnya ditahan oleh sang Raksasa. Tanpa ragu ia menawarkan dirinya sebagai ganti sang ayah. Sang Raksasa menerimanya, dan Belle pun tinggal di istana yang penuh keajaiban dan misteri.",
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "neutral",
        amb: "village",
        tx: "Hari-hari berlalu. Belle dan Raksasa mulai berbicara, berdebat tentang buku, dan tertawa bersama. Belle mulai melihat sosok yang berbeda di balik wajah mengerikan itu — seseorang yang baik hati, kesepian, dan rindu untuk dimengerti.",
      },
      {
        bg: "village",
        char: "dayang",
        mood: "happy",
        amb: "village",
        tx: "Suatu malam, musuh-musuh desa datang menyerang istana. Belle berlari kembali dan melihat Raksasa terluka parah. \"Jangan pergi! Aku... aku mencintaimu.\" Kata-kata itu mengalir dari hatinya yang terdalam, tanpa disengaja.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "happy",
        amb: "village",
        tx: "CAHAYA! Kutukan pun terputus. Di depan Belle berdiri pangeran tampan yang telah lama tersembunyi di balik kutukan. Istana kembali menjadi indah, semua benda kembali menjadi manusia. Belle dan sang pangeran tersenyum — mereka telah menemukan satu sama lain.",
        end: true,
        moral:
          "Jangan menilai seseorang dari penampilannya. Keindahan sejati ada di dalam hati. Cinta yang tulus bisa mengubah bahkan hati yang paling keras sekalipun.",
      },
    ],
  },
];
