"use strict";
/* LENTERA KECIL — Stories v2: narasi lebih kaya, scene lebih hidup */
const DB = [
  {
    id: "ST-001",
    title: "Kancil dan Buaya",
    sub: "Kecerdikan mengalahkan kekuatan",
    emoji: "🦌",
    color: "#f59e0b",
    diff: "Easy",
    dur: "5 mnt",
    tags: ["hewan", "kecerdikan"],
    scenes: [
      {
        bg: "forest",
        char: "kancil",
        mood: "happy",
        amb: "forest",
        tx: "Di tengah hutan belantara yang hijau dan rindang, hiduplah seekor Kancil kecil yang terkenal paling cerdik di antara semua binatang. Matanya selalu berbinar-binar penuh akal!",
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "thinking",
        amb: "forest",
        tx: 'Hari itu perut Kancil keroncongan. Ia mencium aroma buah-buahan segar yang harum dari seberang sungai. "Pasti rasanya manis sekali," pikirnya sambil menelan ludah.',
      },
      {
        bg: "river",
        char: "kancil",
        mood: "thinking",
        amb: "river",
        tx: "Tapi sungai itu lebar dan deras sekali. Di permukaan air yang berkilau, Kancil bisa melihat bayangan punggung hitam para Buaya yang mengintai di bawah permukaan. Bahaya mengancam!",
      },
      {
        bg: "river",
        char: "buaya",
        mood: "angry",
        amb: "river",
        tx: '"Hei Kancil kecil!" suara menggelegar memecah kesunyian. Kepala Buaya muncul dari air, memperlihatkan deretan gigi tajamnya. "Berani-beraninya kamu mendekati sungaiku! Pergi sebelum aku makan kamu!"',
      },
      {
        bg: "river",
        char: "kancil",
        mood: "clever",
        amb: "river",
        tx: 'Kancil tidak gentar sedikit pun. Otaknya berputar cepat. Tiba-tiba ia punya ide cemerlang! "Wahai Buaya yang terhormat, aku datang membawa pesan penting dari Raja Hutan. Beliau ingin menghitung jumlah kalian untuk memberikan hadiah!"',
      },
      {
        bg: "river",
        char: "buaya",
        mood: "neutral",
        amb: "river",
        tx: 'Para Buaya saling pandang dengan serakah. "Hadiah?! Benarkah?" Tanpa berpikir panjang, mereka berbaris rapi membentang dari tepi ke tepi sungai, punggung mereka berderet seperti batu loncatan.',
      },
      {
        bg: "river",
        char: "kancil",
        mood: "happy",
        amb: "river",
        tx: 'Kancil melompat riang dari punggung satu Buaya ke Buaya lainnya! "Satu... dua... tiga... empat..." Ia menghitung sambil tertawa dalam hati. Kakinya tetap kering, tubuhnya tetap selamat!',
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "laugh",
        amb: "forest",
        tx: 'Setelah tiba di seberang dengan selamat, Kancil berbalik dan berteriak, "Terima kasih Buaya! Tapi sejujurnya, tidak ada hadiah dari Raja Hutan. Hanya kecerdikanku yang membantuku menyeberang!" Ia pun berlari sambil tertawa terbahak-bahak.',
        end: true,
        moral:
          "Kecerdikan dan keberanian lebih kuat daripada kekuatan fisik. Otak yang cerdas adalah senjata terbaik!",
      },
    ],
  },
  {
    id: "ST-002",
    title: "Timun Mas",
    sub: "Keberanian seorang gadis melawan raksasa",
    emoji: "🥒",
    color: "#22c55e",
    diff: "Medium",
    dur: "6 mnt",
    tags: ["keberanian", "magic"],
    scenes: [
      {
        bg: "village",
        char: "ibu",
        mood: "sad",
        amb: "village",
        tx: "Di sebuah desa yang tenang, tinggal seorang ibu yang hatinya selalu rindu. Setiap pagi ia duduk di depan rumahnya yang sunyi, memandang rumput yang dibasahi embun pagi. Ia sangat mendambakan seorang anak.",
      },
      {
        bg: "forest",
        char: "raksasa",
        mood: "neutral",
        amb: "forest",
        tx: 'Suatu malam yang mencekam, muncul seorang Raksasa yang tingginya menyentuh langit. Tanah bergetar saat ia melangkah. "Aku akan memberimu anak dari biji timun ajaib ini," suaranya menggelegar, "tapi saat ia berusia 17 tahun... ia harus menjadi milikku!"',
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Dari biji timun yang ditanam dengan penuh cinta, tumbuh seorang bayi mungil yang cantik jelita. Sang ibu menamainya Timun Mas. Ia tumbuh menjadi gadis yang riang, baik hati, dan selalu mengisi rumah dengan tawa.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "worried",
        amb: "village",
        tx: 'Hari ulang tahun ke-17 Timun Mas pun tiba. Sang ibu yang cemas segera pergi menemui petapa sakti. "Tolong selamatkan anakku!" Petapa itu memberikan empat kantong kecil berisi biji timun, jarum, garam, dan terasi ajaib.',
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "scared",
        amb: "village",
        tx: 'Raksasa datang mengguncang bumi! "Mana anakmu?!" Dengan berlinang air mata, sang ibu memeluk Timun Mas erat-erat. "Larilah Nak, gunakan kantong-kantong ini. Ibu selalu mencintaimu!" Timun Mas pun berlari sekencang angin!',
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "brave",
        amb: "forest",
        tx: "Timun Mas melempar biji timun ke belakangnya — BRAK! Seketika tumbuhlah hutan timun yang sangat lebat dan panjang. Namun Raksasa dengan mudah menerjangnya sambil mengaum marah!",
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "brave",
        amb: "rain",
        tx: "Timun Mas melempar jarum — KRAK! Hutan bambu berduri setinggi menara muncul tiba-tiba. Ia melempar garam — SPLOOSH! Lautan bergelombang menghalangi jalan. Lalu terasi — BLUUB! Lautan lumpur mendidih menggelegak dahsyat!",
      },
      {
        bg: "forest",
        char: "raksasa",
        mood: "defeated",
        amb: "rain",
        tx: "Raksasa yang jahat itu tersedot masuk ke dalam lumpur mendidih yang berputar seperti pusaran. Ia mengaum kesakitan, lalu perlahan tenggelam dan lenyap selamanya. Hutan kembali sunyi dan damai.",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Timun Mas berlari kembali ke desa dan langsung masuk ke pelukan hangat ibunya yang sudah menunggu dengan cemas. Mereka berdua menangis bahagia, berpelukan sangat erat. Keberanian Timun Mas telah menyelamatkan segalanya.",
        end: true,
        moral:
          "Kasih sayang orang tua adalah kekuatan terbesar. Dengan keberanian dan doa, tidak ada rintangan yang tidak bisa diatasi.",
      },
    ],
  },
  {
    id: "ST-003",
    title: "Sangkuriang",
    sub: "Asal-usul Gunung Tangkuban Perahu",
    emoji: "🌋",
    color: "#ef4444",
    diff: "Medium",
    dur: "6 mnt",
    tags: ["legenda"],
    scenes: [
      {
        bg: "forest",
        char: "dayang",
        mood: "happy",
        amb: "forest",
        tx: "Di tanah Sunda yang indah berhias bukit dan sungai jernih, hiduplah Dayang Sumbi, putri yang cantik jelita. Setiap hari ia menenun kain di tepi hutan sambil menikmati kicauan burung dan semilir angin.",
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "surprised",
        amb: "forest",
        tx: "Bertahun-tahun berlalu. Suatu hari datang pemuda yang sangat gagah dan tampan bernama Sangkuriang dari arah hutan. Ia jatuh hati dalam sekejap pada Dayang Sumbi yang tampak masih muda belia. Tapi ada rahasia besar yang tersembunyi...",
      },
      {
        bg: "village",
        char: "dayang",
        mood: "shocked",
        amb: "village",
        tx: 'Saat memeriksa rambut Sangkuriang, Dayang Sumbi menemukan sebuah bekas luka di kepalanya. Jantungnya berhenti sedetik. "Ya Tuhan... ini anakku yang pergi dulu!" Ia harus segera menggagalkan rencana pernikahan ini!',
      },
      {
        bg: "night",
        char: "dayang",
        mood: "clever",
        amb: "night",
        tx: 'Dayang Sumbi berpikir keras. Lalu dengan tenang ia berkata, "Baiklah Sangkuriang. Aku mau menikahimu, asalkan kamu bisa membuat sebuah danau besar dan sebuah perahu raksasa... hanya dalam satu malam saja."',
      },
      {
        bg: "night",
        char: "pemuda",
        mood: "working",
        amb: "night",
        tx: "Sangkuriang menyanggupi! Ia bersemedi memanggil makhluk-makhluk gaib dari seluruh penjuru hutan. Ribuan jin bekerja keras di bawah sinar bulan. Pohon-pohon tumbang, tanah bergetar, air mengalir deras. Hampir selesai!",
      },
      {
        bg: "night",
        char: "ibu",
        mood: "worried",
        amb: "night",
        tx: "Dayang Sumbi panik melihat pekerjaan Sangkuriang hampir rampung menjelang subuh! Ia segera membangunkan para gadis desa untuk menumbuk padi beramai-ramai dan menyalakan api unggun besar di ufuk timur, menipu langit seolah fajar telah tiba.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "angry",
        amb: "village",
        tx: "Ayam-ayam berkokok riuh! Para jin yang ketakutan langsung kabur meninggalkan pekerjaan mereka. Sangkuriang terdiam kaku, lalu meledak dalam amarah yang luar biasa saat menyadari tipu muslihat Dayang Sumbi.",
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "angry",
        amb: "forest",
        tx: "Dalam amarah yang memuncak, Sangkuriang menendang perahu besar yang hampir selesai itu dengan sekuat tenaga. BLAAMMM! Perahu itu melayang tinggi dan jatuh terbalik, menghujam bumi menjadi sebuah gunung besar.",
        end: true,
        moral:
          "Gunung Tangkuban Perahu yang kita lihat hari ini adalah warisan sejarah yang indah. Setiap gunung menyimpan cerita yang menakjubkan!",
      },
    ],
  },
  {
    id: "ST-004",
    title: "Bawang Merah & Bawang Putih",
    sub: "Kebaikan selalu berbuah kebaikan",
    emoji: "🧅",
    color: "#a855f7",
    diff: "Easy",
    dur: "5 mnt",
    tags: ["kebaikan", "keluarga"],
    scenes: [
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Di desa yang subur, hiduplah dua saudara tiri yang sangat berbeda. Bawang Putih selalu bangun pagi, menyapu halaman, dan membantu tetangga dengan senyum tulus. Sementara Bawang Merah masih tidur sambil bermimpi tentang emas.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "angry",
        amb: "village",
        tx: 'Ibu tiri dan Bawang Merah suka memerintah Bawang Putih seenaknya. "Cuci baju! Masak nasi! Bersihkan kandang!" Tapi Bawang Putih tidak pernah mengeluh. Ia mengerjakannya sambil bersenandung pelan.',
      },
      {
        bg: "river",
        char: "timunsmas",
        mood: "sad",
        amb: "river",
        tx: "Saat mencuci di sungai, kain Bawang Putih terseret arus dan hanyut. Ia mengikutinya jauh ke hilir, sampai menemukan sebuah gubuk tua di tepi sungai. Seorang nenek yang sangat tua duduk di sana, tersenyum ramah.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "happy",
        amb: "village",
        tx: '"Maukah kamu membantuku membersihkan rumah?" tanya nenek lembut. Bawang Putih langsung mengerjakan segalanya dengan bersemangat — menyapu, mengepel, memasak. Nenek sangat senang dan terkesan dengan ketulusan gadis itu.',
      },
      {
        bg: "river",
        char: "timunsmas",
        mood: "surprised",
        amb: "village",
        tx: '"Pilihkan satu hadiah," kata nenek sambil menunjuk dua labu besar dan kecil. Bawang Putih dengan rendah hati memilih yang kecil. Di rumah, saat dibelah, labu kecil itu berisi tumpukan emas, permata, dan kain sutra yang indah!',
      },
      {
        bg: "river",
        char: "buaya",
        mood: "neutral",
        amb: "river",
        tx: "Bawang Merah yang sangat iri langsung menghanyutkan kainnya sendiri. Ia berlari ke rumah nenek tua itu, tapi bekerja dengan setengah hati, sering mengeluh, dan selalu cemberut. Nenek hanya menggeleng pelan melihat sikapnya.",
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "angry",
        amb: "village",
        tx: "Bawang Merah dengan tamak langsung merampas labu yang paling besar! Ia berlari pulang sambil membayangkan kekayaan yang akan didapat. Namun saat labu itu dibelah di rumah... keluarlah ular, kalajengking, dan lebah yang langsung menyerangnya!",
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Bawang Merah dan ibunya berlari ketakutan. Setelah tenang, mereka datang memohon maaf pada Bawang Putih dengan tulus. Bawang Putih memaafkan mereka dengan lapang dada, dan mereka pun akhirnya hidup rukun bersama.",
        end: true,
        moral:
          "Kebaikan hati dan kerendahan hati selalu membawa berkah. Keserakahan dan iri hati hanya mendatangkan kesulitan.",
      },
    ],
  },
  {
    id: "ST-005",
    title: "Malin Kundang",
    sub: "Pentingnya menghormati orang tua",
    emoji: "⛵",
    color: "#0ea5e9",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["keluarga", "hormat"],
    scenes: [
      {
        bg: "sea",
        char: "ibu",
        mood: "happy",
        amb: "sea",
        tx: "Di tepi pantai yang berbatu-batu, hiduplah seorang ibu dan anak lelaki bernama Malin Kundang. Mereka sangat miskin, namun selalu bahagia bersama. Sang ibu bekerja keras menangkap ikan setiap hari untuk menghidupi Malin.",
      },
      {
        bg: "sea",
        char: "pemuda",
        mood: "happy",
        amb: "sea",
        tx: 'Saat Malin beranjak dewasa, ia berpamitan untuk merantau mencari keberuntungan. "Ibu, tunggu aku pulang membawa emas!" Dengan perahu pedagang kaya, ia berlayar mengarungi lautan luas yang berombak.',
      },
      {
        bg: "sea",
        char: "pemuda",
        mood: "happy",
        amb: "sea",
        tx: "Bertahun-tahun berlalu. Malin berhasil menjadi saudagar yang sangat kaya. Ia menikah dengan putri bangsawan yang cantik. Kapal-kapalnya berlayar di berbagai lautan, membawa rempah dan emas. Ia melupakan desa kecilnya.",
      },
      {
        bg: "sea",
        char: "ibu",
        mood: "happy",
        amb: "sea",
        tx: 'Kabar kepulangan Malin sampai ke desa. Sang ibu yang sudah menua segera berlari ke pantai dengan kaki gemetar. Air matanya mengalir melihat kapal mewah berlabuh. "Malin! Anakku! Ibu sudah rindu sekali!"',
      },
      {
        bg: "sea",
        char: "pemuda",
        mood: "angry",
        amb: "sea",
        tx: 'Malin berdiri tegak di dek kapal yang megah, memandang ke bawah. Istrinya yang anggun berdiri di sampingnya. Malin merasa sangat malu. "Pergi kamu, wanita tua! Aku tidak mengenalmu! Aku tidak punya ibu sepertimu!" Kata-kata itu menghantam lebih keras dari ombak.',
      },
      {
        bg: "rain",
        char: "ibu",
        mood: "sad",
        amb: "rain",
        tx: "Sang ibu berdiri mematung. Air matanya bercampur dengan rintik hujan yang mulai turun. Hatinya yang hancur perlahan membara menjadi doa. Dengan suara yang gemetar ia mengangkat tangannya ke langit yang mulai menghitam...",
      },
      {
        bg: "rain",
        char: "pemuda",
        mood: "scared",
        amb: "rain",
        tx: 'Badai datang tiba-tiba! Petir menyambar-nyambar, ombak setinggi gunung menghantam kapal Malin. Malin berlutut gemetar ketakutan. "Ibu, ampunkan aku!" Tapi suaranya tenggelam dalam auman badai yang semakin ganas.',
        end: true,
        moral:
          "Hormati orang tuamu dengan sepenuh hati. Kasih ibu tidak ternilai harganya. Jangan pernah menyakiti hati mereka yang telah membesarkanmu.",
      },
    ],
  },
  {
    id: "ST-006",
    title: "Si Kera dan Buaya",
    sub: "Kecerdasan mengalahkan pengkhianatan",
    emoji: "🐒",
    color: "#f97316",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["hewan", "kecerdikan"],
    scenes: [
      {
        bg: "forest",
        char: "kancil",
        mood: "happy",
        amb: "forest",
        tx: "Di pohon ara yang tinggi di tepi sungai, tinggal seekor Kera yang lincah. Ia punya sahabat karib seekor Buaya besar. Setiap hari Kera dengan senang hati melempar buah-buahan manis ke mulut Buaya yang menunggu di bawah.",
      },
      {
        bg: "river",
        char: "buaya",
        mood: "neutral",
        amb: "river",
        tx: 'Istri Buaya jatuh sakit parah. Tabib berkata dengan serius, "Satu-satunya obatnya adalah hati Kera segar. Tanpa itu, istrimu tidak bisa sembuh." Buaya terdiam lama, menatap punggung sahabatnya dengan perasaan bersalah.',
      },
      {
        bg: "river",
        char: "buaya",
        mood: "neutral",
        amb: "river",
        tx: '"Kera, ayo ikut aku! Istriku ingin bertemu denganmu," bujuk Buaya. Kera melompat gembira ke punggung sahabatnya. Buaya berenang pelan menuju tengah sungai yang dalam. Arus di sini sangat deras...',
      },
      {
        bg: "river",
        char: "buaya",
        mood: "angry",
        amb: "river",
        tx: 'Di tengah sungai yang dalam, Buaya berhenti. Dengan nada berat ia berkata, "Maafkan aku Kera... tapi aku membutuhkan hatimu untuk menyembuhkan istriku." Kera terdiam sesaat. Jantungnya berdegup kencang. Tapi otaknya berputar sangat cepat!',
      },
      {
        bg: "river",
        char: "kancil",
        mood: "clever",
        amb: "river",
        tx: '"Aduh, mengapa kamu tidak bilang dari tadi?!" seru Kera sambil menepuk dahinya pura-pura. "Hatiku tertinggal di pohon ara tadi! Cepat kembalilah ke tepi, aku ambilkan hatiku!" Buaya yang polos langsung berbalik tanpa curiga.',
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "laugh",
        amb: "forest",
        tx: 'Begitu punggung Buaya menyentuh tepi sungai, Kera melompat setinggi-tingginya ke dahan pohon yang aman! Dari atas ia berteriak, "Bodohnya kamu Buaya! Apakah ada makhluk yang bisa meninggalkan hatinya di pohon? Kau telah mengkhianati persahabatan kita!"',
        end: true,
        moral:
          "Kecerdasan bisa menyelamatkan nyawa. Mengkhianati persahabatan sejati adalah kesalahan yang sangat menyedihkan.",
      },
    ],
  },
  {
    id: "ST-007",
    title: "Putri Tangguk",
    sub: "Bersyukur atas rezeki yang ada",
    emoji: "🌾",
    color: "#84cc16",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["kebaikan", "syukur"],
    scenes: [
      {
        bg: "village",
        char: "ibu",
        mood: "happy",
        amb: "village",
        tx: "Di desa yang hijau subur, Putri Tangguk terkenal sebagai petani paling beruntung. Sawahnya yang kecil selalu menghasilkan padi berlimpah — cukup untuk dimakan, dijual, dan diberikan ke tetangga. Semua orang kagum dengan keberkahannya.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "angry",
        amb: "village",
        tx: 'Namun anehnya, Putri Tangguk tidak pernah merasa cukup. Setiap hari ia mengeluh, "Capek sekali harus panen terus! Lumbungku sudah terlalu penuh, pusing aku lihatnya!" Suatu hari yang naas, ia membuang nasi yang masih baik ke tanah dengan kesal.',
      },
      {
        bg: "forest",
        char: "dayang",
        mood: "sad",
        amb: "night",
        tx: 'Malam itu, Putri Tangguk bermimpi. Seorang wanita cantik bercahaya berdiri di depannya. "Akulah Dewi Padi. Aku telah memberkahi sawahmu dengan penuh kasih. Tapi kamu membuang rezekimu dengan sembarangan. Sangat menyakitkan hatiku."',
      },
      {
        bg: "village",
        char: "ibu",
        mood: "shocked",
        amb: "village",
        tx: "Putri Tangguk terbangun dengan jantung berdegup. Ia berlari ke sawah... kosong! Berlari ke lumbung... kosong! Semua padi, semua beras, lenyap tanpa jejak. Ia jatuh berlutut dan menangis sejadi-jadinya.",
        end: true,
        moral:
          "Bersyukur adalah kunci kebahagiaan sejati. Hargai setiap rezeki yang kamu miliki, sekecil apapun itu, karena rezeki bisa pergi seketika.",
      },
    ],
  },
  {
    id: "ST-008",
    title: "Roro Jonggrang",
    sub: "Legenda Candi Prambanan yang megah",
    emoji: "🏛️",
    color: "#ec4899",
    diff: "Medium",
    dur: "6 mnt",
    tags: ["legenda"],
    scenes: [
      {
        bg: "village",
        char: "dayang",
        mood: "happy",
        amb: "village",
        tx: "Di Kerajaan Prambanan yang megah berdiri Roro Jonggrang, putri mahkota yang kecantikannya bagaikan rembulan. Rambut hitamnya panjang terurai, matanya berbinar seperti bintang. Seluruh negeri terpesona padanya.",
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "neutral",
        amb: "village",
        tx: "Dari kerajaan seberang datanglah Bandung Bondowoso, pangeran sakti mandraguna yang bisa menggerakkan batu dengan pikirannya. Ia langsung jatuh hati dan melamar Roro Jonggrang dengan upacara yang sangat mewah.",
      },
      {
        bg: "village",
        char: "dayang",
        mood: "clever",
        amb: "village",
        tx: 'Roro Jonggrang tidak mau dipaksa menikah. Ia berpikir keras mencari cara untuk menolak tanpa membuat perang. Tiba-tiba muncul ide. "Baiklah Bandung, aku mau menjadi istrimu... tapi dengan satu syarat yang harus kamu penuhi dulu."',
      },
      {
        bg: "night",
        char: "raksasa",
        mood: "neutral",
        amb: "night",
        tx: '"Bangunkan aku seribu candi yang megah dalam satu malam!" tantang Roro Jonggrang. Bandung Bondowoso menutup matanya, bersemedi. Tanah berguncang. Dari segala penjuru datanglah ribuan jin yang siap bekerja. Pekerjaan dimulai!',
      },
      {
        bg: "night",
        char: "ibu",
        mood: "worried",
        amb: "night",
        tx: 'Roro Jonggrang menghitung dengan jantung berdebar. Candi ke-900, ke-950, ke-990... hampir subuh! Candi ke-999 mau selesai! Ia berlari membangunkan seluruh gadis desa. "Cepat, tumbuk padi! Nyalakan api besar di timur! Sekarang!"',
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "angry",
        amb: "village",
        tx: "Langit di timur memerah seolah fajar. Ayam-ayam berkokok riuh! Para jin panik dan berhamburan pergi meninggalkan pekerjaan. Candi ke-1000 tidak selesai. Bandung Bondowoso berjalan mendekat dengan langkah berat dan mata yang memerah.",
      },
      {
        bg: "village",
        char: "dayang",
        mood: "shocked",
        amb: "village",
        tx: '"Roro Jonggrang! Kamu yang membunyikan fajar palsu itu!" tuduh Bandung dengan suara mengguncang tanah. "Karena kamu curang, maka jadilah kamu arca batu! Kamu akan melengkapi candi-candiku sebagai yang ke-1000!" Seketika tubuh Roro Jonggrang membatu.',
        end: true,
        moral:
          "Candi Prambanan yang indah itu menyimpan kisah ini. Kejujuran selalu lebih baik daripada kecurangan, seberapapun sulitnya.",
      },
    ],
  },
  {
    id: "ST-009",
    title: "Lutung Kasarung",
    sub: "Kebaikan hati membuahkan keajaiban",
    emoji: "🐒",
    color: "#78716c",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["kebaikan", "magic"],
    scenes: [
      {
        bg: "forest",
        char: "dayang",
        mood: "sad",
        amb: "forest",
        tx: 'Purbasari, putri kerajaan yang paling baik hati, dibuang ke hutan gelap oleh kakaknya yang jahat karena fitnah. Sendirian di antara pohon-pohon besar, ia duduk menangis pelan. "Mungkin ini takdirku," bisiknya.',
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "happy",
        amb: "forest",
        tx: "Namun ia tidak sendirian lama. Seekor lutung hitam berbulu lebat muncul dari balik semak. Dengan gerakan lembut, ia meletakkan buah-buahan segar di depan Purbasari. Setiap hari ia setia menjaga sang putri dari bahaya hutan.",
      },
      {
        bg: "forest",
        char: "dayang",
        mood: "happy",
        amb: "forest",
        tx: "Purbasari mulai sayang pada Lutung Kasarung. Ia bercerita padanya, bernyanyi untuknya, dan memperlakukannya seperti sahabat terbaik. Ia tidak pernah memandang rendah si lutung berbulu hitam itu walau sedetik pun.",
      },
      {
        bg: "night",
        char: "pemuda",
        mood: "surprised",
        amb: "night",
        tx: 'Malam bulan purnama yang indah. Sinar perak membasahi hutan. Tiba-tiba Lutung Kasarung bercahaya! Bulu-bulunya rontok, berganti dengan sosok pangeran tampan berwibawa. "Aku Guru Minda dari kahyangan yang dikutuk. Kamu telah membebaskanku dengan ketulusanmu."',
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Sang pangeran membawa Purbasari kembali ke kerajaan dengan penuh kemuliaan. Kakak yang jahat pun menerima ganjaran atas perbuatannya. Purbasari dan Guru Minda hidup bahagia, dan hutan pun kembali senyap dalam kedamaian.",
        end: true,
        moral:
          "Kebaikan hati yang tulus punya kekuatan ajaib. Perlakukan semua makhluk dengan kasih, karena kita tidak pernah tahu siapa yang ada di balik penampilannya.",
      },
    ],
  },
  {
    id: "ST-010",
    title: "Si Pitung",
    sub: "Pahlawan rakyat Betawi yang pemberani",
    emoji: "🦸",
    color: "#14b8a6",
    diff: "Medium",
    dur: "4 mnt",
    tags: ["keberanian", "kebaikan"],
    scenes: [
      {
        bg: "village",
        char: "pemuda",
        mood: "brave",
        amb: "village",
        tx: "Di kampung Betawi yang ramai di tepi Batavia, lahir dan tumbuh seorang pemuda bernama Pitung. Setiap fajar ia sudah bangun untuk mengaji, dan setiap hari ia berlatih silat di bawah bimbingan gurunya yang bijak.",
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "angry",
        amb: "village",
        tx: "Namun kampungnya ditindas. Para tuan tanah Belanda memungut pajak yang sangat berat. Petani yang tidak mampu membayar akan diusir dari tanahnya sendiri. Warga menangis kelaparan, tapi tidak ada yang berani melawan.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "brave",
        amb: "village",
        tx: "Pitung tidak tahan melihat penderitaan itu. Dengan ilmu silatnya yang tinggi dan keberanian yang membara, ia mulai menggerebek gudang-gudang tuan tanah kaya di malam hari, lalu membagikan hasilnya ke rakyat yang kelaparan.",
      },
      {
        bg: "night",
        char: "pemuda",
        mood: "brave",
        amb: "night",
        tx: "Kompeni Belanda mengerahkan pasukan untuk menangkap Pitung. Tapi rakyat selalu melindunginya — menyembunyikannya di rumah, memberinya makan, memperingatkannya dari bahaya. Pitung selalu selangkah lebih cepat dari para pengejarnya.",
        end: true,
        moral:
          "Keberanian untuk membela yang lemah adalah tindakan mulia. Gunakan kemampuan dan kekuatanmu untuk kebaikan orang banyak.",
      },
    ],
  },
  {
    id: "ST-011",
    title: "Gadis dan Cermin Ajaib",
    sub: "Kecantikan sejati ada di dalam hati",
    emoji: "🪞",
    color: "#6366f1",
    diff: "Easy",
    dur: "3 mnt",
    tags: ["kebaikan"],
    scenes: [
      {
        bg: "village",
        char: "timunsmas",
        mood: "sad",
        amb: "village",
        tx: 'Sari adalah gadis desa yang selalu diremehkan teman-temannya. "Bajumu jelek! Rambutmu tidak rapi!" ejek mereka. Namun Sari tetap tersenyum. Ia percaya ada sesuatu yang lebih penting dari penampilan luar.',
      },
      {
        bg: "forest",
        char: "dayang",
        mood: "neutral",
        amb: "forest",
        tx: 'Suatu hari di pinggir hutan, Sari menemukan cermin kuno yang bercahaya lembut. Rasa penasaran mendorongnya untuk bertanya, "Cermin ajaib, apa sebenarnya kecantikan sejati itu?" Cermin itu menjawab dengan cahaya yang hangat, "Kecantikan sejati bersinar dari hati yang baik dan tulus."',
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Sari menyimpan jawaban itu di hatinya. Ia semakin rajin membantu tetangga yang susah, merawat orang tua yang sakit, dan selalu menyambut semua orang dengan senyum yang tulus. Perlahan, sinar kebaikannya mulai dirasakan semua orang.",
        end: true,
        moral:
          "Kecantikan sejati bukan tentang penampilan fisik, melainkan tentang kebaikan dan ketulusan hati yang bersinar dari dalam.",
      },
    ],
  },
  {
    id: "ST-012",
    title: "Anak Gembala dan Serigala",
    sub: "Akibat berbohong kepada orang yang mempercayaimu",
    emoji: "🐑",
    color: "#64748b",
    diff: "Easy",
    dur: "3 mnt",
    tags: ["kejujuran", "hewan"],
    scenes: [
      {
        bg: "forest",
        char: "kancil",
        mood: "happy",
        amb: "forest",
        tx: 'Di padang rumput yang luas dan hijau, Budi setiap hari menggembalakan puluhan domba milik keluarganya. Hari-harinya terasa sangat membosankan. Ia ingin membuat sesuatu yang "menarik" terjadi.',
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "laugh",
        amb: "forest",
        tx: 'Tiba-tiba Budi berteriak sekeras-kerasnya, "SERIGALA! SERIGALA ADA DI SINI!" Para petani berlari dari sawah membawa cangkul dan sabit. Tapi tidak ada apa-apa. Budi tertawa terpingkal-pingkal melihat mereka kelelahan. "Hahaha, kalian tertipu!"',
      },
      {
        bg: "forest",
        char: "raksasa",
        mood: "angry",
        amb: "forest",
        tx: 'Esok harinya, serigala berbulu abu-abu yang lapar sungguh-sungguh datang mengintai kawanan domba! Budi berlari dan berteriak sambil melambaikan tangan, "TOLONG! SERIGALA! SERIGALA SUNGGUHAN!" Tapi tidak ada seorangpun yang datang.',
      },
      {
        bg: "forest",
        char: "pemuda",
        mood: "sad",
        amb: "forest",
        tx: 'Domba-domba Budi berpencar ketakutan dan berhasil dicuri serigala. Budi duduk di tanah sambil menangis pilu. Pak tua tetangganya datang dan berkata dengan lembut, "Budi, inilah akibatnya jika kita bermain-main dengan kepercayaan orang lain."',
        end: true,
        moral:
          "Kejujuran adalah pondasi kepercayaan. Sekali kamu berbohong, kepercayaan orang lain padamu akan sulit pulih kembali.",
      },
    ],
  },
  {
    id: "ST-013",
    title: "Legenda Danau Toba",
    sub: "Asal-usul danau vulkanik terbesar dunia",
    emoji: "🏞️",
    color: "#06b6d4",
    diff: "Medium",
    dur: "5 mnt",
    tags: ["legenda"],
    scenes: [
      {
        bg: "river",
        char: "pemuda",
        mood: "happy",
        amb: "river",
        tx: "Di lembah hijau yang dikelilingi bukit-bukit menjulang, Toba seorang pemuda sederhana menjalani hidupnya sebagai nelayan. Suatu sore yang cerah, jalanya menangkap sesuatu yang berkilau emas di dalam air jernih.",
      },
      {
        bg: "river",
        char: "dayang",
        mood: "surprised",
        amb: "river",
        tx: 'Ikan itu bergerak aneh di tangannya... lalu POOF! Berubah menjadi seorang gadis cantik bercahaya dengan rambut basah tergerai. "Namaku Putri. Kamu telah menyelamatkanku. Aku akan menikahimu, tapi ingat satu janji penting: jangan pernah ceritakan asal-usulku kepada siapapun."',
      },
      {
        bg: "village",
        char: "timunsmas",
        mood: "happy",
        amb: "village",
        tx: "Mereka menikah dan dikaruniai anak lelaki yang nakal bernama Samosir. Kehidupan mereka bahagia. Toba bekerja keras di sawah setiap hari, dan Putri mengurus rumah dengan penuh kasih. Desa pun menjadi makmur dan tentram.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "angry",
        amb: "village",
        tx: 'Suatu siang Toba pulang dari sawah dalam keadaan sangat lelah dan lapar. Samosir belum mengantarkan bekalnya. Ketika ia temukan anaknya sedang bermain, kemarahannya meledak. "Dasar anak ikan! Tidak berguna!" Kata-kata itu terucap begitu saja.',
      },
      {
        bg: "rain",
        char: "dayang",
        mood: "sad",
        amb: "rain",
        tx: 'Langit mendadak gelap. Angin kencang berhembus. Putri muncul dengan wajah sedih namun tenang. "Kamu telah melanggar janjimu, Toba. Aku harus kembali." Hujan lebat turun, tidak berhenti. Air terus naik dan naik...',
      },
      {
        bg: "sea",
        char: "pemuda",
        mood: "sad",
        amb: "river",
        tx: "Lembah itu perlahan tergenang air dan berubah menjadi danau yang sangat luas dan dalam. Samosir berlari ke bukit yang kini menjadi pulau di tengah danau. Danau indah itu kita kenal sekarang sebagai Danau Toba, dan pulau di tengahnya adalah Pulau Samosir.",
        end: true,
        moral:
          "Sebuah janji adalah ikatan suci. Jaga perkataanmu, karena kata-kata yang terucap tidak bisa ditarik kembali.",
      },
    ],
  },
  {
    id: "ST-014",
    title: "Kelinci dan Kura-Kura",
    sub: "Ketekunan selalu mengalahkan kesombongan",
    emoji: "🐢",
    color: "#10b981",
    diff: "Easy",
    dur: "4 mnt",
    tags: ["hewan", "ketekunan"],
    scenes: [
      {
        bg: "forest",
        char: "kancil",
        mood: "happy",
        amb: "forest",
        tx: 'Di hutan yang rindang, Kelinci adalah bintangnya. Ia bisa berlari lebih cepat dari semua binatang dan sangat suka pamer. "Lihat aku!" teriaknya sambil berlari berputar-putar. "Tak ada yang bisa menandingi kecepatanku!"',
      },
      {
        bg: "forest",
        char: "buaya",
        mood: "neutral",
        amb: "forest",
        tx: 'Kura-kura yang sedang berjalan lambat di dekatnya berkata dengan tenang, "Kamu memang cepat Kelinci. Tapi bagaimana kalau kita berlomba saja? Dari pohon beringin ini sampai ke batu besar di ujung hutan." Semua binatang terdiam kaget.',
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "laugh",
        amb: "forest",
        tx: 'Kelinci tertawa terpingkal-pingkal sampai perutnya sakit. Binatang-binatang lain juga ikut tertawa. Tapi Kura-kura tidak bergeming. Wajahnya tetap tenang dan penuh keyakinan. "Aku serius, Kelinci. Maukah kamu?"',
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "thinking",
        amb: "forest",
        tx: 'Lomba pun dimulai! Kelinci melesat secepat kilat, meninggalkan Kura-kura jauh di belakang. Setelah setengah perjalanan, Kelinci berhenti dan merebahkan diri di bawah pohon yang teduh. "Kura-kura pasti masih sangat jauh di belakang. Aku tidur sebentar saja..."',
      },
      {
        bg: "forest",
        char: "buaya",
        mood: "happy",
        amb: "forest",
        tx: "Kura-kura terus melangkah. Satu langkah, dua langkah, pelan tapi pasti. Saat melewati Kelinci yang mendengkur keras, ia tidak berhenti. Ia terus berjalan, terus berjalan, sampai akhirnya... batu besar di ujung hutan terlihat di depannya!",
      },
      {
        bg: "forest",
        char: "kancil",
        mood: "shocked",
        amb: "forest",
        tx: "KRIUK! Suara ranting patah membangunkan Kelinci. Ia membuka mata... batu besar itu masih jauh! Ia berlari sekencang mungkin, tapi ketika tiba di garis finish, Kura-kura sudah duduk di sana dengan senyum tenangnya. Semua binatang bersorak keras!",
        end: true,
        moral:
          "Ketekunan dan konsistensi tanpa henti akan selalu mengalahkan bakat yang tidak diimbangi kerja keras dan kerendahan hati.",
      },
    ],
  },
  {
    id: "ST-015",
    title: "Ande-Ande Lumut",
    sub: "Menjaga hati diri adalah kekuatan sejati",
    emoji: "💚",
    color: "#4ade80",
    diff: "Medium",
    dur: "4 mnt",
    tags: ["keluarga", "kebaikan"],
    scenes: [
      {
        bg: "village",
        char: "timunsmas",
        mood: "sad",
        amb: "village",
        tx: "Kleting Kuning menjalani hidupnya dengan sabar di bawah perintah ibu dan saudara-saudara tirinya. Setiap pagi ia mengambil air, memasak, mencuci — sementara mereka masih bermain dan bermalas-malasan. Tapi senyumnya tak pernah padam.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "happy",
        amb: "village",
        tx: "Kabar angin berhembus ke seluruh desa: Pangeran Ande-Ande Lumut yang tampan, bijaksana, dan kaya sedang mencari istri yang tepat! Kleting Biru, Kleting Hijau, dan Kleting Merah — saudara-saudara tirinya — langsung bersemangat berhias diri.",
      },
      {
        bg: "river",
        char: "buaya",
        mood: "neutral",
        amb: "river",
        tx: "Untuk sampai ke tempat sang pangeran, semua orang harus menyeberangi sungai yang dijaga Yuyu Kangkang, kepiting raksasa yang jahat. Ia mau menyeberangkan para gadis, tapi dengan syarat yang sangat merendahkan martabat mereka.",
      },
      {
        bg: "river",
        char: "timunsmas",
        mood: "brave",
        amb: "river",
        tx: 'Saudara-saudara tiri Kleting Kuning memilih menerima syarat itu demi bisa bertemu pangeran. Tapi saat tiba giliran Kleting Kuning, ia dengan tegas menggeleng. "Aku lebih baik tidak bertemu pangeran manapun daripada harus merendahkan diriku!" Ia menyeberang sendiri dengan susah payah.',
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "happy",
        amb: "village",
        tx: 'Di hadapan sang pangeran, Kleting Kuning berdiri dengan pakaian basah dan kusut. Namun Ande-Ande Lumut berdiri dan memilih tepat di depannya. "Hanya kamu yang datang dengan hati yang terjaga bersih. Itu jauh lebih berharga dari seribu mahkota emas."',
        end: true,
        moral:
          "Menjaga harga diri dan kehormatan adalah tindakan terkuat yang bisa dilakukan seseorang. Orang yang tepat akan selalu menghargainya.",
      },
    ],
  },
  {
    id: "ST-016",
    title: "Cahaya yang Mengubah Kegelapan",
    sub: "Kebaikan tulus menembus hati yang paling keras",
    emoji: "🌟",
    color: "#f59e0b",
    diff: "Easy",
    dur: "3 mnt",
    tags: ["kebaikan"],
    scenes: [
      {
        bg: "night",
        char: "raksasa",
        mood: "angry",
        amb: "night",
        tx: "Di ujung hutan yang paling gelap, tinggal seorang penyihir tua yang ditakuti semua orang. Dulu ia baik, tapi bertahun-tahun hidup sendirian dan dikucilkan membuat hatinya mengeras seperti batu karang.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "brave",
        amb: "village",
        tx: 'Mpu Bahula, murid muda yang bijak, memilih mendatangi si penyihir sendirian. Ia tidak membawa senjata, hanya membawa makanan dan senyum tulus. "Bolehkah aku belajar darimu, tuan? Aku percaya kamu punya banyak kebijaksanaan untuk dibagikan."',
      },
      {
        bg: "village",
        char: "raksasa",
        mood: "neutral",
        amb: "village",
        tx: "Si penyihir mencurigai Mpu Bahula. Tapi pemuda itu datang setiap hari, merawatnya saat sakit, mendengarkan ceritanya dengan sabar. Perlahan, seperti es yang mencair terkena hangat matahari, hati si penyihir mulai melunak.",
      },
      {
        bg: "forest",
        char: "timunsmas",
        mood: "happy",
        amb: "forest",
        tx: "Kegelapan yang pernah menutup hati si penyihir perlahan berubah menjadi cahaya. Ia mulai menggunakan ilmunya untuk menyembuhkan dan membantu. Desa pun berubah dari ketakutan menjadi penuh kasih. Satu kebaikan telah mengubah segalanya.",
        end: true,
        moral:
          "Kebaikan yang tulus, kesabaran, dan kepercayaan adalah senjata paling kuat untuk mengubah kegelapan menjadi cahaya.",
      },
    ],
  },
  {
    id: "ST-017",
    title: "Surat untuk Ibu",
    sub: "Tidak ada kata terlambat untuk pulang",
    emoji: "💌",
    color: "#f43f5e",
    diff: "Easy",
    dur: "3 mnt",
    tags: ["keluarga"],
    scenes: [
      {
        bg: "village",
        char: "pemuda",
        mood: "sad",
        amb: "village",
        tx: "Raka merantau ke kota besar dengan mimpi yang menggebu. Bulan berlalu menjadi tahun. Pekerjaan, teman baru, dan kehidupan kota yang sibuk membuatnya lupa. Lupa untuk menelepon. Lupa untuk menulis. Lupa untuk pulang.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "sad",
        amb: "village",
        tx: "Di desa, sang ibu berdiri di depan pintu setiap sore menjelang matahari tenggelam. Matanya selalu menatap jalan setapak yang membelah ladang. Di mejanya selalu ada makanan kesukaan Raka yang masih hangat, siapa tahu ia tiba-tiba pulang.",
      },
      {
        bg: "village",
        char: "pemuda",
        mood: "sad",
        amb: "village",
        tx: "Suatu malam, Raka melihat foto lama di dompetnya — ia dan ibunya saat ia masih kecil. Air matanya tidak bisa ditahan. Ia segera mengambil kertas dan menulis surat panjang berisi semua penyesalannya, lalu membeli tiket bus untuk pulang.",
      },
      {
        bg: "village",
        char: "ibu",
        mood: "happy",
        amb: "village",
        tx: 'Saat Raka turun dari bus, ibunya sudah berdiri di ujung jalan dengan mata yang berkaca-kaca. Tidak ada kata marah. Hanya pelukan hangat yang sangat panjang. "Pulang saja, Nak. Rumah selalu menunggumu." Raka menangis dalam pelukan yang paling hangat di dunia.',
        end: true,
        moral:
          "Kasih ibu tidak pernah habis dan tidak pernah menyimpan dendam. Jangan biarkan kesibukan membuatmu lupa pulang kepada orang-orang yang menyayangimu.",
      },
    ],
  },
];
